export const PROFILE_GROUP_TABS = [
  { id: 'start_here', label: '00_ESSENTIAL VIBES' },
  { id: 'people', label: '01_SKIN & PORTRAIT' },
  { id: 'cinema', label: '02_CINEMATIC STORIES' },
  { id: 'color', label: '03_COLOR ENERGY' },
  { id: 'landscape', label: '04_NATURE & LIGHT' },
  { id: 'bw', label: '05_MONO MOOD' },
  { id: 'night', label: '06_NIGHT VIBES' },
  { id: 'creative', label: '07_CREATIVE LAB' },
  { id: 'pro', label: '08_PRO CONTROL' },
];

const PROFILE_GROUP_DATA = {
  start_here: [
    ['gold_200', 'Golden Mood – Warm Classic'],
    ['portra_400', 'Soft Portrait – Natural Glow'],
    ['vision3_250d', 'Cinematic Film – Soft Story'],
    ['ektar_100', 'Vivid Colors – High Punch'],
    ['bw_hp5', 'Classic B&W – Timeless Look'],
    ['cinestill_800t', 'Neon Night – Cinematic Glow'],
  ],
  people: [
    ['portra_160', 'Soft Portrait – Clean Skin'],
    ['portra_400', 'Soft Portrait – Natural Glow'],
    ['portra_800', 'Soft Portrait – Low Light Glow'],
    ['portra_400', 'Editorial Skin – Soft Warm'],
    ['fuji_400h', 'Pastel Portrait – Airy Skin'],
    ['fuji_400h_cc', 'Pastel Portrait – Film Soft'],
    ['pro_neg_std', 'Studio Skin – Clean Tone'],
    ['fuji_astia_100f', 'Soft Fashion – Gentle Contrast'],
    ['astia_cc', 'Soft Fashion – Film Pastel'],
    ['senova_light', 'Light Skin – Bright Air'],
    ['dreamneg', 'Dream Skin – Soft Fade'],
    ['fuji_nostalgic_neg', 'Nostalgic Skin – Film Fade'],
  ],
  cinema: [
    ['asteroid_city_kodak_vision_t200_v1', 'Pastel Cinema – Soft Vintage Story'],
    ['asteroid_city_kodak_vision_t200_v2', 'Pastel Cinema – Warm Retro Mood'],
    ['blue_velvet_cinestill_50d', 'Moody Cinema – Blue Shadows'],
    ['cinechrome', 'Cinematic Clean – Film Tone'],
    ['cinestill_50d', 'Daylight Cinema – Natural Film'],
    ['cinestill_800', 'Low Light Cinema – Soft Grain'],
    ['cinestill_800t', 'Neon Night – Cinematic Glow'],
    ['cinestill_x', 'Cinematic Punch – Film Boost'],
    ['classic_cinema', 'Classic Film – Neutral Story'],
    ['fuji_eterna', 'Soft Cinema – Film Wash'],
    ['sony_eterna', 'Digital Cinema – Soft Film'],
    ['vision3_50d', 'Bright Cinema – Clean Daylight'],
    ['vision3_250d', 'Balanced Cinema – Natural Skin'],
    ['vision3_200t', 'Indoor Cinema – Warm Film'],
    ['vision3_200t_plus', 'Indoor Cinema – Rich Tone'],
    ['vision3_500t', 'Night Cinema – Deep Shadows'],
  ],
  color: [
    ['gold_200', 'Golden Mood – Warm Classic'],
    ['gold_luxe', 'Golden Mood – Rich Luxury'],
    ['kodak_gold_v1', 'Golden Classic – Soft Warm'],
    ['kodak_gold_v2', 'Golden Classic – Deep Warm'],
    ['colorplus_200', 'Warm Everyday – Vintage Tone'],
    ['kodak_color_plus_200_cc', 'Warm Everyday – Film Boost'],
    ['solara_100_cc', 'Sunny Day – Light Warm'],
    ['solara_100_cc', 'Sunny Day – Soft Film'],
    ['kodak_solara_100', 'Sunny Vintage – Clean Warm'],
    ['amarelo_30d', 'Sun Kiss – Yellow Warm'],
    ['ektar_100', 'Vivid Colors – High Punch'],
    ['ektar_100_cc', 'Vivid Colors – Film Boost'],
    ['vektro100', 'Color Pop – Digital Punch'],
    ['ultramax_400', 'Color Pop – Everyday Film'],
    ['procolor', 'Balanced Color – Clean Pop'],
    ['gaf_500', 'Retro Color – Bold Tone'],
    ['chroma_fade', 'Soft Color – Washed Film'],
    ['crimson', 'Deep Red – Cinematic Tone'],
    ['rose_spectra', 'Rose Tone – Soft Pink'],
    ['leicachrome', 'Luxury Color – Leica Feel'],
    ['zetra_100', 'Neutral Film – Soft Color'],
    ['oktar', 'Neutral Film – Soft Color'],
    ['kodak_oktar', 'Neutral Film – Soft Color'],
  ],
  landscape: [
    ['velvia_pro', 'Landscape Pro – Rich Greens'],
    ['fuji_velvia_50', 'Landscape Pro – Vivid Nature'],
    ['fuji_provia_100f', 'Landscape Clean – Neutral Color'],
    ['fuji_provia_cc', 'Landscape Clean – Film Tone'],
    ['fuji_provia_rx', 'Landscape Boost – Extra Clarity'],
    ['provia_rx_cc', 'Landscape Boost – Film Look'],
    ['fortia_50_cc', 'Nature Pop – Saturated Light'],
    ['fuji_fortia_50', 'Nature Pop – Strong Colors'],
  ],
  bw: [
    ['bw_hp5', 'Classic B&W – Documentary Look'],
    ['bw_trix_400', 'Street B&W – Hard Contrast'],
    ['bw_trix_1600', 'Street B&W – High Grain'],
    ['bw_tmax_100', 'Fine Art B&W – Clean Sharp'],
    ['bw_tmax_400', 'Fine Art B&W – Balanced'],
    ['bw_delta_100', 'Soft B&W – Smooth Tone'],
    ['bw_delta_3200', 'Raw B&W – High Grain'],
    ['bw_foma_100', 'Vintage B&W – Soft Fade'],
    ['bw_foma_400', 'Vintage B&W – Grain Mood'],
    ['bw_arista_edu_100', 'Classic B&W – Student Film'],
    ['bw_xp2', 'Modern B&W – Clean Contrast'],
    ['bw_vision', 'Cinema B&W – Film Look'],
    ['bw_kosmo_pan', 'Retro B&W – Flat Tone'],
    ['acros_x', 'Artistic B&W – Experimental'],
    ['acros_xg', 'Artistic B&W – Experimental'],
    ['acros_xr', 'Artistic B&W – Experimental'],
    ['acros_xy', 'Artistic B&W – Experimental'],
  ],
  night: [
    ['cinestill_800t', 'Neon Night – Film Glow'],
    ['fuji_natura_1600', 'Night Street – Soft Grain'],
    ['fuji_superia_1600', 'Night Flash – Urban Look'],
    ['fuji_superia_400', 'Street Color – Classic Film'],
    ['neo_max', 'Urban Mood – Clean Shadows'],
    ['vespera', 'Evening Mood – Soft Dark'],
  ],
  creative: [
    ['redscale_ultra', 'Red Film – Warm Burn'],
    ['redscale_ultra_cc', 'Red Film – Deep Burn'],
    ['midred_infra', 'Infrared Look – Dream Red'],
    ['acidnom', 'Acid Tone – Experimental Color'],
    ['classic_chrome', 'Muted Color – Editorial'],
    ['sony_nostalgic_neg', 'Nostalgic Film – Soft Fade'],
    ['sony_classic_negative', 'Classic Film – Digital Soft'],
    ['sony_standard_cl', 'Clean Standard – Neutral Look'],
    ['evproplus', 'Pro Look – Clean Boost'],
    ['estra_500', 'Film Grain – Cinematic Noise'],
    ['x_tarr', 'Cool Tone – Cinematic Blue'],
    ['veniliqum', 'Art Tone – Stylized Color'],
    ['zero_mute', 'Muted Mood – Low Contrast'],
    ['phenomena', 'Creative Tone – Experimental'],
    ['magic_spice', 'Warm Mood – Cinematic Spice'],
    ['harman_phoenix', 'Analog Fade – Soft Vintage'],
    ['phoenix_harman', 'Analog Fade – Soft Vintage'],
  ],
  pro: [
    ['portra_400', 'Portra 400 – Base'],
    ['ektar_100', 'Ektar 100 – Base'],
    ['cinestill_800t', 'Cinestill 800T – Base'],
    ['vision3_250d', 'Vision3 250D – Base'],
    ['bw_hp5', 'HP5 – Base'],
  ],
};

function buildGroupEntries(groupId, items) {
  return items.map(([sourceId, title, description], index) => ({
    group: groupId,
    order: index + 1,
    sourceId,
    title,
    description: String(description ?? sourceId),
  }));
}

export const CURATED_PROFILE_ENTRIES = PROFILE_GROUP_TABS.flatMap((tab) =>
  buildGroupEntries(tab.id, PROFILE_GROUP_DATA[tab.id] ?? [])
);
