--[[
  Prefiks `MindfulLens` w polu `profile` musi dokładnie odpowiadać nazwie profilu
  osadzonej w binarnych plikach `.dcp` (Camera Raw). Zmiana na „Analog Signature”
  wymaga przebudowy DCP i ponownej instalacji profili z menu wtyczki.
]]
local LrPathUtils = import "LrPathUtils"

local function pluginLoad(relativePath)
    return dofile(LrPathUtils.child(_PLUGIN.path, relativePath))
end

local publicCatalog = pluginLoad("lib/PublicCatalog.lua")

local M = {}

M.emulsions = {
    {
        id = "portra_160",
        label = "Kodak Portra 160",
        profile = "MindfulLens Kodak Portra 160",
        dcpFile = "AI_KM_PORTRA_160.dcp",
        foundationPreset = "profiles/foundation/portra_160_foundation.xmp",
        lutFile = "profiles/luts/portra_160.cube",
    },
    {
        id = "portra_400",
        label = "Kodak Portra 400",
        profile = "MindfulLens Kodak Portra 400",
        dcpFile = "AI_KM_PORTRA_400.dcp",
        foundationPreset = "profiles/foundation/portra_400_foundation.xmp",
        lutFile = "profiles/luts/portra_400.cube",
        microTune = {
            Contrast2012 = -2,
            HueAdjustmentBlue = -2,
            SaturationAdjustmentOrange = 3,
            LuminanceAdjustmentOrange = 2,
            SaturationAdjustmentAqua = -2,
            SaturationAdjustmentBlue = -3,
        },
    },
    {
        id = "portra_800",
        label = "Kodak Portra 800",
        profile = "MindfulLens Kodak Portra 800",
        dcpFile = "AI_KM_PORTRA_800.dcp",
        foundationPreset = "profiles/foundation/portra_800_foundation.xmp",
        lutFile = "profiles/luts/portra_800.cube",
        microTune = {
            Contrast2012 = -2,
            SaturationAdjustmentOrange = 3,
            LuminanceAdjustmentOrange = 1,
            SaturationAdjustmentYellow = -1,
            SaturationAdjustmentAqua = -1,
            SaturationAdjustmentBlue = -2,
            LuminanceAdjustmentBlue = 0,
        },
    },
    {
        id = "gold_200",
        label = "Kodak Gold 200",
        profile = "MindfulLens Kodak Gold 200",
        dcpFile = "AI_KM_GOLD_200.dcp",
        foundationPreset = "profiles/foundation/gold_200_foundation.xmp",
        lutFile = "profiles/luts/gold_200.cube",
        microTune = {
            Contrast2012 = 3,
            HueAdjustmentYellow = -3,
            SaturationAdjustmentOrange = 5,
            SaturationAdjustmentYellow = 4,
            LuminanceAdjustmentBlue = -2,
        },
    },
    {
        id = "colorplus_200",
        label = "Kodak ColorPlus 200",
        profile = "MindfulLens Kodak ColorPlus 200",
        dcpFile = "AI_KM_COLORPLUS_200.dcp",
        foundationPreset = "profiles/foundation/colorplus_200_foundation.xmp",
        lutFile = "profiles/luts/colorplus_200.cube",
        microTune = {
            Contrast2012 = -2,
            BlueHue = -2,
            SaturationAdjustmentYellow = -4,
            SaturationAdjustmentGreen = -5,
            LuminanceAdjustmentOrange = 2,
        },
    },
    {
        id = "ektar_100",
        label = "Kodak Ektar 100",
        profile = "MindfulLens Kodak Ektar 100",
        dcpFile = "AI_KM_EKTAR_100.dcp",
        foundationPreset = "profiles/foundation/ektar_100_foundation.xmp",
        lutFile = "profiles/luts/ektar_100.cube",
        microTune = {
            Contrast2012 = 2,
            HueAdjustmentBlue = -2,
            SaturationAdjustmentRed = 4,
            SaturationAdjustmentBlue = 4,
            LuminanceAdjustmentRed = -1,
            LuminanceAdjustmentBlue = -3,
        },
    },
    {
        id = "ultramax_400",
        label = "Kodak Ultra Max 400",
        profile = "MindfulLens Kodak Ultra Max 400",
        dcpFile = "AI_KM_ULTRAMAX_400.dcp",
        foundationPreset = "profiles/foundation/ultramax_400_foundation.xmp",
        lutFile = "profiles/luts/ultramax_400.cube",
        microTune = {
            Texture = 3,
            SaturationAdjustmentOrange = 2,
            SaturationAdjustmentYellow = -6,
            SaturationAdjustmentAqua = -8,
            LuminanceAdjustmentOrange = 4,
            LuminanceAdjustmentBlue = 3,
        },
    },
    {
        id = "ektachrome",
        label = "Kodak Ektachrome",
        profile = "MindfulLens Kodak Ektachrome",
        dcpFile = "AI_KM_EKTACHROME.dcp",
        foundationPreset = "profiles/foundation/ektachrome_foundation.xmp",
        lutFile = "profiles/luts/ektachrome.cube",
    },
    {
        id = "cinestill_800t",
        label = "CineStill 800T",
        profile = "MindfulLens CineStill 800T",
        dcpFile = "AI_KM_CINESTILL_800T.dcp",
        foundationPreset = "profiles/foundation/cinestill_800t_foundation.xmp",
        lutFile = "profiles/luts/cinestill_800t.cube",
    },
    {
        id = "cinestill_50d",
        label = "CineStill 50D",
        profile = "MindfulLens CineStill 50D",
        dcpFile = "AI_KM_CINESTILL_50D.dcp",
        foundationPreset = "profiles/foundation/cinestill_50d_foundation.xmp",
        lutFile = "profiles/luts/cinestill_50d.cube",
        microTune = {
            Contrast2012 = -1,
            HueAdjustmentBlue = 2,
            SaturationAdjustmentGreen = -2,
            LuminanceAdjustmentOrange = 4,
        },
    },
    {
        id = "fuji_400h",
        label = "Fuji Pro 400H",
        profile = "MindfulLens Fuji Pro 400H",
        dcpFile = "AI_KM_FUJI_400H.dcp",
        foundationPreset = "profiles/foundation/fuji_400h_foundation.xmp",
        lutFile = "profiles/luts/fuji_400h.cube",
    },
    {
        id = "fuji_superia_400",
        label = "Fuji Superia X-Tra 400",
        profile = "MindfulLens Fuji Superia X-Tra 400",
        dcpFile = "AI_KM_FUJI_SUPERIA_400.dcp",
        foundationPreset = "profiles/foundation/fuji_superia_400_foundation.xmp",
        lutFile = "profiles/luts/fuji_superia_400.cube",
    },
    {
        id = "fuji_natura_1600",
        label = "Fuji Natura 1600",
        profile = "MindfulLens Fuji Natura 1600",
        dcpFile = "AI_KM_FUJI_NATURA_1600.dcp",
        foundationPreset = "profiles/foundation/fuji_natura_1600_foundation.xmp",
        lutFile = "profiles/luts/fuji_natura_1600.cube",
    },
    {
        id = "fuji_superia_1600",
        label = "Fuji Superia 1600",
        profile = "MindfulLens Fuji Superia 1600",
        dcpFile = "AI_KM_FUJI_SUPERIA_1600.dcp",
        foundationPreset = "profiles/foundation/fuji_superia_1600_foundation.xmp",
        lutFile = "profiles/luts/fuji_superia_1600.cube",
    },
    {
        id = "fuji_velvia_50",
        label = "Fuji Velvia 50",
        profile = "MindfulLens Fuji Velvia 50",
        dcpFile = "AI_KM_FUJI_VELVIA_50.dcp",
        foundationPreset = "profiles/foundation/fuji_velvia_50_foundation.xmp",
        lutFile = "profiles/luts/fuji_velvia_50.cube",
    },
    {
        id = "fuji_astia_100f",
        label = "Fuji Astia 100F",
        profile = "MindfulLens Fuji Astia 100F",
        dcpFile = "AI_KM_FUJI_ASTIA_100F.dcp",
        foundationPreset = "profiles/foundation/fuji_astia_100f_foundation.xmp",
        lutFile = "profiles/luts/fuji_astia_100f.cube",
    },
    {
        id = "fuji_provia_100f",
        label = "Fuji Provia 100F",
        profile = "MindfulLens Fuji Provia 100F",
        dcpFile = "AI_KM_FUJI_PROVIA_100F.dcp",
        foundationPreset = "profiles/foundation/fuji_provia_100f_foundation.xmp",
        lutFile = "profiles/luts/fuji_provia_100f.cube",
        microTune = {
            Contrast2012 = 3,
            HueAdjustmentBlue = -3,
            SaturationAdjustmentAqua = 3,
            SaturationAdjustmentBlue = 5,
            SaturationAdjustmentYellow = -2,
            LuminanceAdjustmentBlue = -2,
        },
    },
    {
        id = "fuji_provia_rx",
        label = "Fuji Provia RX",
        profile = "MindfulLens Fuji Provia RX",
        dcpFile = "AI_KM_FUJI_PROVIA_RX.dcp",
        foundationPreset = "profiles/foundation/fuji_provia_rx_foundation.xmp",
        lutFile = "profiles/luts/fuji_provia_rx.cube",
    },
    {
        id = "fuji_fortia_50",
        label = "Fuji Fortia 50",
        profile = "MindfulLens Fuji Fortia 50",
        dcpFile = "AI_KM_FUJI_FORTIA_50.dcp",
        foundationPreset = "profiles/foundation/fuji_fortia_50_foundation.xmp",
        lutFile = "profiles/luts/fuji_fortia_50.cube",
    },
    {
        id = "vision3_50d",
        label = "Kodak Vision3 50D",
        profile = "MindfulLens Kodak Vision3 50D",
        dcpFile = "AI_KM_VISION3_50D.dcp",
        foundationPreset = "profiles/foundation/vision3_50d_foundation.xmp",
        lutFile = "profiles/luts/vision3_50d.cube",
        microTune = {
            Contrast2012 = 1,
            SaturationAdjustmentOrange = 1,
            LuminanceAdjustmentOrange = 4,
            HueAdjustmentBlue = 2,
        },
    },
    {
        id = "vision3_250d",
        label = "Kodak Vision3 250D",
        profile = "MindfulLens Kodak Vision3 250D",
        dcpFile = "AI_KM_VISION3_250D.dcp",
        foundationPreset = "profiles/foundation/vision3_250d_foundation.xmp",
        lutFile = "profiles/luts/vision3_250d.cube",
        microTune = {
            Contrast2012 = -2,
            HueAdjustmentAqua = 4,
            HueAdjustmentBlue = 4,
            SaturationAdjustmentBlue = 2,
            LuminanceAdjustmentBlue = -4,
        },
    },
    {
        id = "vision3_200t",
        label = "Kodak Vision3 200T",
        profile = "MindfulLens Kodak Vision3 200T",
        dcpFile = "AI_KM_VISION3_200T.dcp",
        foundationPreset = "profiles/foundation/vision3_200t_foundation.xmp",
        lutFile = "profiles/luts/vision3_200t.cube",
        microTune = {
            BlueHue = -4,
            SaturationAdjustmentGreen = -6,
            SaturationAdjustmentBlue = -4,
            LuminanceAdjustmentOrange = 4,
            LuminanceAdjustmentBlue = -3,
        },
    },
    {
        id = "vision3_200t_plus",
        label = "Kodak Vision3 200T Plus",
        profile = "MindfulLens Kodak Vision3 200T Plus",
        dcpFile = "AI_KM_VISION3_200T_PLUS.dcp",
        foundationPreset = "profiles/foundation/vision3_200t_plus_foundation.xmp",
        lutFile = "profiles/luts/vision3_200t_plus.cube",
        microTune = {
            Texture = 2,
            SaturationAdjustmentAqua = 3,
            SaturationAdjustmentBlue = 5,
            LuminanceAdjustmentAqua = -4,
            LuminanceAdjustmentBlue = -4,
        },
    },
    {
        id = "vision3_500t",
        label = "Kodak Vision3 500T",
        profile = "MindfulLens Kodak Vision3 500T",
        dcpFile = "AI_KM_VISION3_500T.dcp",
        foundationPreset = "profiles/foundation/vision3_500t_foundation.xmp",
        lutFile = "profiles/luts/vision3_500t.cube",
        microTune = {
            Contrast2012 = -3,
            HueAdjustmentAqua = 10,
            HueAdjustmentBlue = 12,
            SaturationAdjustmentAqua = 6,
            SaturationAdjustmentBlue = 8,
            LuminanceAdjustmentBlue = -6,
        },
    },
    {
        id = "kodachrome_25",
        label = "Kodachrome 25",
        profile = "MindfulLens Kodachrome 25",
        dcpFile = "AI_KM_KODACHROME_25.dcp",
        foundationPreset = "profiles/foundation/kodachrome_25_foundation.xmp",
        lutFile = "profiles/luts/kodachrome_25.cube",
    },
    {
        id = "kodachrome_64",
        label = "Kodachrome 64",
        profile = "MindfulLens Kodachrome 64",
        dcpFile = "AI_KM_KODACHROME_64.dcp",
        foundationPreset = "profiles/foundation/kodachrome_64_foundation.xmp",
        lutFile = "profiles/luts/kodachrome_64.cube",
    },
    {
        id = "kodak_oktar",
        label = "Kodak Oktar",
        profile = "MindfulLens Kodak Oktar",
        dcpFile = "AI_KM_KODAK_OKTAR.dcp",
        foundationPreset = "profiles/foundation/kodak_oktar_foundation.xmp",
        lutFile = "profiles/luts/kodak_oktar.cube",
    },
    {
        id = "agfa_precisa",
        label = "Agfa Precisa",
        profile = "MindfulLens Agfa Precisa",
        dcpFile = "AI_KM_AGFA_PRECISA.dcp",
        foundationPreset = "profiles/foundation/agfa_precisa_foundation.xmp",
        lutFile = "profiles/luts/agfa_precisa.cube",
    },
    {
        id = "redscale_ultra",
        label = "Redscale Ultra",
        profile = "MindfulLens Redscale Ultra",
        dcpFile = "AI_KM_REDSCALE_ULTRA.dcp",
        foundationPreset = "profiles/foundation/redscale_ultra_foundation.xmp",
        lutFile = "profiles/luts/redscale_ultra.cube",
    },
    {
        id = "harman_phoenix",
        label = "Harman Phoenix",
        profile = "MindfulLens Harman Phoenix",
        dcpFile = "AI_KM_HARMAN_PHOENIX.dcp",
        foundationPreset = "profiles/foundation/harman_phoenix_foundation.xmp",
        lutFile = "profiles/luts/harman_phoenix.cube",
    },
    {
        id = "gaf_500",
        label = "GAF 500",
        profile = "MindfulLens GAF 500",
        dcpFile = "AI_KM_GAF_500.dcp",
        foundationPreset = "profiles/foundation/gaf_500_foundation.xmp",
        lutFile = "profiles/luts/gaf_500.cube",
    },
    {
        id = "eastman_cn_ii_100",
        label = "Eastman Color Negative II 100",
        profile = "MindfulLens Eastman Color Negative II 100",
        dcpFile = "AI_KM_EASTMAN_CN_II_100.dcp",
        foundationPreset = "profiles/foundation/eastman_cn_ii_100_foundation.xmp",
        lutFile = "profiles/luts/eastman_cn_ii_100.cube",
    },
    {
        id = "kodak_solara_100",
        label = "Kodak Solara 100",
        profile = "MindfulLens Kodak Solara 100",
        dcpFile = "AI_KM_KODAK_SOLARA_100.dcp",
        foundationPreset = "profiles/foundation/kodak_solara_100_foundation.xmp",
        lutFile = "profiles/luts/kodak_solara_100.cube",
    },
    {
        id = "bw_trix_400",
        label = "Kodak Tri-X 400",
        profile = "MindfulLens Kodak Tri-X 400",
        dcpFile = "AI_KM_BW_TRIX_400.dcp",
        foundationPreset = "profiles/foundation/bw_trix_400_foundation.xmp",
        lutFile = "profiles/luts/bw_trix_400.cube",
        bw = true,
    },
    {
        id = "bw_trix_1600",
        label = "Kodak Tri-X 1600",
        profile = "MindfulLens Kodak Tri-X 1600",
        dcpFile = "AI_KM_BW_TRIX_1600.dcp",
        foundationPreset = "profiles/foundation/bw_trix_1600_foundation.xmp",
        lutFile = "profiles/luts/bw_trix_1600.cube",
        bw = true,
    },
    {
        id = "bw_xp2",
        label = "Ilford XP2 Super",
        profile = "MindfulLens Ilford XP2 Super",
        dcpFile = "AI_KM_BW_XP2.dcp",
        foundationPreset = "profiles/foundation/bw_xp2_foundation.xmp",
        lutFile = "profiles/luts/bw_xp2.cube",
        bw = true,
    },
    {
        id = "bw_tmax_400",
        label = "Kodak T-Max 400",
        profile = "MindfulLens Kodak T-Max 400",
        dcpFile = "AI_KM_BW_TMAX_400.dcp",
        foundationPreset = "profiles/foundation/bw_tmax_400_foundation.xmp",
        lutFile = "profiles/luts/bw_tmax_400.cube",
        bw = true,
    },
    {
        id = "bw_tmax_100",
        label = "Kodak T-Max 100",
        profile = "MindfulLens Kodak T-Max 100",
        dcpFile = "AI_KM_BW_TMAX_100.dcp",
        foundationPreset = "profiles/foundation/bw_tmax_100_foundation.xmp",
        lutFile = "profiles/luts/bw_tmax_100.cube",
        bw = true,
    },
    {
        id = "bw_foma_100",
        label = "Fomapan 100",
        profile = "MindfulLens Fomapan 100",
        dcpFile = "AI_KM_BW_FOMA_100.dcp",
        foundationPreset = "profiles/foundation/bw_foma_100_foundation.xmp",
        lutFile = "profiles/luts/bw_foma_100.cube",
        bw = true,
    },
    {
        id = "bw_arista_edu_100",
        label = "Arista EDU 100",
        profile = "MindfulLens Arista EDU 100",
        dcpFile = "AI_KM_BW_ARISTA_EDU_100.dcp",
        foundationPreset = "profiles/foundation/bw_arista_edu_100_foundation.xmp",
        lutFile = "profiles/luts/bw_arista_edu_100.cube",
        bw = true,
    },
    {
        id = "bw_hp5",
        label = "Ilford HP5 400",
        profile = "MindfulLens Ilford HP5 400",
        dcpFile = "AI_KM_BW_HP5.dcp",
        foundationPreset = "profiles/foundation/bw_hp5_foundation.xmp",
        lutFile = "profiles/luts/bw_hp5.cube",
        bw = true,
    },
    {
        id = "bw_delta_3200",
        label = "Ilford Delta 3200",
        profile = "MindfulLens Ilford Delta 3200",
        dcpFile = "AI_KM_BW_DELTA_3200.dcp",
        foundationPreset = "profiles/foundation/bw_delta_3200_foundation.xmp",
        lutFile = "profiles/luts/bw_delta_3200.cube",
        bw = true,
    },
    {
        id = "bw_kosmo_pan",
        label = "Kosmo Pan",
        profile = "MindfulLens Kosmo Pan",
        dcpFile = "AI_KM_BW_KOSMO_PAN.dcp",
        foundationPreset = "profiles/foundation/bw_kosmo_pan_foundation.xmp",
        lutFile = "profiles/luts/bw_kosmo_pan.cube",
        bw = true,
    },
    {
        id = "bw_vision",
        label = "Kodak Vision3 BW",
        profile = "MindfulLens Kodak Vision3 BW",
        dcpFile = "AI_KM_BW_VISION.dcp",
        foundationPreset = "profiles/foundation/bw_vision_foundation.xmp",
        lutFile = "profiles/luts/bw_vision.cube",
        bw = true,
    },
    {
        id = "bw_foma_400",
        label = "Fomapan 400",
        profile = "MindfulLens Fomapan 400",
        dcpFile = "AI_KM_BW_FOMA_400.dcp",
        foundationPreset = "profiles/foundation/bw_foma_400_foundation.xmp",
        lutFile = "profiles/luts/bw_foma_400.cube",
        bw = true,
    },
    {
        id = "bw_delta_100",
        label = "Ilford Delta 100",
        profile = "MindfulLens Ilford Delta 100",
        dcpFile = "AI_KM_BW_DELTA_100.dcp",
        foundationPreset = "profiles/foundation/bw_delta_100_foundation.xmp",
        lutFile = "profiles/luts/bw_delta_100.cube",
        bw = true,
    },
    {
        id = "sony_standard_cl",
        label = "Sony Standard CL",
        profile = "MindfulLens Sony Standard CL",
        dcpFile = "AI_KM_SONY_STANDARD_CL.dcp",
        foundationPreset = "profiles/foundation/sony_standard_cl_foundation.xmp",
        lutFile = "profiles/luts/sony_standard_cl.cube",
        microTune = {
            SaturationAdjustmentOrange = 1,
            LuminanceAdjustmentOrange = 2,
            ColorGradeBlending = 44,
        },
    },
    {
        id = "vektro100",
        label = "Vektro100",
        profile = "MindfulLens Vektro100",
        dcpFile = "AI_KM_VEKTRO100.dcp",
        foundationPreset = "profiles/foundation/vektro100_foundation.xmp",
        lutFile = "profiles/luts/vektro100.cube",
        microTune = {
            Contrast2012 = 1,
            SaturationAdjustmentOrange = 2,
            SaturationAdjustmentBlue = 1,
            ColorGradeBalance = -1,
        },
    },
    {
        id = "senova_light",
        label = "Senova Light",
        profile = "MindfulLens Senova Light",
        dcpFile = "AI_KM_SENOVA_LIGHT.dcp",
        foundationPreset = "profiles/foundation/senova_light_foundation.xmp",
        lutFile = "profiles/luts/senova_light.cube",
        microTune = {
            Contrast2012 = -2,
            Clarity2012 = -1,
            LuminanceAdjustmentOrange = 3,
            ColorGradeHighlightsSat = 1,
        },
    },
    {
        id = "evproplus",
        label = "Evpro+",
        profile = "MindfulLens Evpro+",
        dcpFile = "AI_KM_EVPROPLUS.dcp",
        foundationPreset = "profiles/foundation/evproplus_foundation.xmp",
        lutFile = "profiles/luts/evproplus.cube",
        microTune = {
            Contrast2012 = 2,
            Clarity2012 = 1,
            SaturationAdjustmentBlue = 2,
            ColorGradeShadowsSat = 3,
        },
    },
    {
        id = "kodak_gold_v1",
        label = "Kodak Gold V1",
        profile = "MindfulLens Kodak Gold V1",
        dcpFile = "AI_KM_KODAK_GOLD_V1.dcp",
        foundationPreset = "profiles/foundation/kodak_gold_v1_foundation.xmp",
        lutFile = "profiles/luts/kodak_gold_v1.cube",
        microTune = {
            Contrast2012 = -1,
            HueAdjustmentYellow = -2,
            SaturationAdjustmentOrange = 4,
            SaturationAdjustmentGreen = -6,
            LuminanceAdjustmentOrange = 3,
        },
    },
    {
        id = "kodak_gold_v2",
        label = "Kodak Gold V2",
        profile = "MindfulLens Kodak Gold V2",
        dcpFile = "AI_KM_KODAK_GOLD_V2.dcp",
        foundationPreset = "profiles/foundation/kodak_gold_v2_foundation.xmp",
        lutFile = "profiles/luts/kodak_gold_v2.cube",
        microTune = {
            Contrast2012 = 1,
            HueAdjustmentYellow = -2,
            SaturationAdjustmentOrange = 5,
            SaturationAdjustmentGreen = -7,
            LuminanceAdjustmentOrange = 3,
        },
    },
    {
        id = "kodachrome_v1",
        label = "Kodachrome V1",
        profile = "MindfulLens Kodachrome V1",
        dcpFile = "AI_KM_KODACHROME_V1.dcp",
        foundationPreset = "profiles/foundation/kodachrome_v1_foundation.xmp",
        lutFile = "profiles/luts/kodachrome_v1.cube",
        microTune = {
            Contrast2012 = 2,
            Clarity2012 = 2,
            SaturationAdjustmentRed = 4,
            SaturationAdjustmentBlue = 8,
            LuminanceAdjustmentBlue = -8,
        },
    },
    {
        id = "kodachrome_v2",
        label = "Kodachrome V2",
        profile = "MindfulLens Kodachrome V2",
        dcpFile = "AI_KM_KODACHROME_V2.dcp",
        foundationPreset = "profiles/foundation/kodachrome_v2_foundation.xmp",
        lutFile = "profiles/luts/kodachrome_v2.cube",
        microTune = {
            Contrast2012 = 3,
            Clarity2012 = 3,
            SaturationAdjustmentRed = 5,
            SaturationAdjustmentYellow = 2,
            SaturationAdjustmentBlue = 10,
            LuminanceAdjustmentBlue = -10,
        },
    },
    {
        id = "kodachrome_v3",
        label = "Kodachrome V3",
        profile = "MindfulLens Kodachrome V3",
        dcpFile = "AI_KM_KODACHROME_V3.dcp",
        foundationPreset = "profiles/foundation/kodachrome_v3_foundation.xmp",
        lutFile = "profiles/luts/kodachrome_v3.cube",
        microTune = {
            Contrast2012 = 1,
            Clarity2012 = 1,
            SaturationAdjustmentRed = 3,
            SaturationAdjustmentBlue = 6,
            LuminanceAdjustmentBlue = -6,
        },
    },
    {
        id = "leicachrome",
        label = "Leicachrome",
        profile = "MindfulLens Leicachrome",
        dcpFile = "AI_KM_LEICACHROME.dcp",
        foundationPreset = "profiles/foundation/leicachrome_foundation.xmp",
        lutFile = "profiles/luts/leicachrome.cube",
        microTune = {
            Contrast2012 = 2,
            Clarity2012 = 2,
            SaturationAdjustmentRed = 2,
            SaturationAdjustmentBlue = 6,
            LuminanceAdjustmentBlue = -6,
        },
    },
    {
        id = "velvia_pro",
        label = "Velvia Pro",
        profile = "MindfulLens Velvia Pro",
        dcpFile = "AI_KM_VELVIA_PRO.dcp",
        foundationPreset = "profiles/foundation/velvia_pro_foundation.xmp",
        lutFile = "profiles/luts/velvia_pro.cube",
        microTune = {
            Contrast2012 = 2,
            Clarity2012 = 1,
            SaturationAdjustmentYellow = 8,
            SaturationAdjustmentGreen = 12,
            SaturationAdjustmentBlue = 8,
            LuminanceAdjustmentBlue = -10,
        },
    },
    {
        id = "classic_chrome",
        label = "Classic Chrome",
        profile = "MindfulLens Classic Chrome",
        dcpFile = "AI_KM_CLASSIC_CHROME.dcp",
        foundationPreset = "profiles/foundation/classic_chrome_foundation.xmp",
        lutFile = "profiles/luts/classic_chrome.cube",
        microTune = {
            Contrast2012 = -2,
            HueAdjustmentGreen = 6,
            SaturationAdjustmentOrange = -4,
            SaturationAdjustmentBlue = -6,
            LuminanceAdjustmentBlue = -4,
        },
    },
    {
        id = "pro_neg_std",
        label = "Pro Neg Std",
        profile = "MindfulLens Pro Neg Std",
        dcpFile = "AI_KM_PRO_NEG_STD.dcp",
        foundationPreset = "profiles/foundation/pro_neg_std_foundation.xmp",
        lutFile = "profiles/luts/pro_neg_std.cube",
        microTune = {
            Contrast2012 = -2,
            SaturationAdjustmentOrange = -1,
            LuminanceAdjustmentOrange = 3,
            ColorGradeBalance = -2,
        },
    },
    {
        id = "sony_classic_negative",
        label = "Sony Classic Negative",
        profile = "MindfulLens Sony Classic Negative",
        dcpFile = "AI_KM_SONY_CLASSIC_NEGATIVE.dcp",
        foundationPreset = "profiles/foundation/sony_classic_negative_foundation.xmp",
        lutFile = "profiles/luts/sony_classic_negative.cube",
        microTune = {
            HueAdjustmentGreen = 5,
            SaturationAdjustmentBlue = -4,
            LuminanceAdjustmentOrange = 3,
            ColorGradeBalance = -4,
        },
    },
    {
        id = "fuji_nostalgic_neg",
        label = "Fuji Nostalgic Neg",
        profile = "MindfulLens Fuji Nostalgic Neg",
        dcpFile = "AI_KM_FUJI_NOSTALGIC_NEG.dcp",
        foundationPreset = "profiles/foundation/fuji_nostalgic_neg_foundation.xmp",
        lutFile = "profiles/luts/fuji_nostalgic_neg.cube",
        microTune = {
            Contrast2012 = -1,
            HueAdjustmentOrange = 2,
            SaturationAdjustmentOrange = 2,
            SaturationAdjustmentGreen = -3,
            LuminanceAdjustmentOrange = 3,
        },
    },
    {
        id = "fuji_eterna",
        label = "Fuji Eterna",
        profile = "MindfulLens Fuji Eterna",
        dcpFile = "AI_KM_FUJI_ETERNA.dcp",
        foundationPreset = "profiles/foundation/fuji_eterna_foundation.xmp",
        lutFile = "profiles/luts/fuji_eterna.cube",
        microTune = {
            Contrast2012 = -2,
            Clarity2012 = -1,
            SaturationAdjustmentGreen = -4,
            SaturationAdjustmentBlue = -2,
            LuminanceAdjustmentOrange = 2,
        },
    },
    {
        id = "sony_eterna",
        label = "Sony Eterna",
        profile = "MindfulLens Sony Eterna",
        dcpFile = "AI_KM_SONY_ETERNA.dcp",
        foundationPreset = "profiles/foundation/sony_eterna_foundation.xmp",
        lutFile = "profiles/luts/sony_eterna.cube",
        microTune = {
            Contrast2012 = -2,
            SaturationAdjustmentGreen = -3,
            SaturationAdjustmentBlue = -2,
            LuminanceAdjustmentOrange = 2,
        },
    },
	    {
	        id = "acros_x",
	        label = "Acros X",
	        profile = "MindfulLens Acros X",
	        dcpFile = "AI_KM_ACROS_X.dcp",
	        foundationPreset = "profiles/foundation/acros_x_foundation.xmp",
	        lutFile = "profiles/luts/acros_x.cube",
	        microTune = {
	            Contrast2012 = 2,
	            Clarity2012 = 4,
	            Texture = 6,
	            ColorGradeMidtoneSat = 4,
	        },
	        bw = true,
	    },
	    {
	        id = "acros_xy",
	        label = "Acros XY",
	        profile = "MindfulLens Acros XY",
	        dcpFile = "AI_KM_ACROS_XY.dcp",
	        foundationPreset = "profiles/foundation/acros_xy_foundation.xmp",
	        lutFile = "profiles/luts/acros_xy.cube",
	        microTune = {
	            GrayMixerYellow = 12,
	            GrayMixerBlue = -16,
	            Texture = 5,
	            ColorGradeMidtoneSat = 4,
	        },
	        bw = true,
	    },
	    {
	        id = "acros_xr",
	        label = "Acros XR",
	        profile = "MindfulLens Acros XR",
	        dcpFile = "AI_KM_ACROS_XR.dcp",
	        foundationPreset = "profiles/foundation/acros_xr_foundation.xmp",
	        lutFile = "profiles/luts/acros_xr.cube",
	        microTune = {
	            Contrast2012 = 3,
	            GrayMixerRed = 18,
	            GrayMixerBlue = -18,
	            Texture = 6,
	        },
	        bw = true,
	    },
	    {
	        id = "acros_xg",
	        label = "Acros XG",
	        profile = "MindfulLens Acros XG",
	        dcpFile = "AI_KM_ACROS_XG.dcp",
	        foundationPreset = "profiles/foundation/acros_xg_foundation.xmp",
	        lutFile = "profiles/luts/acros_xg.cube",
	        microTune = {
	            GrayMixerGreen = 16,
	            GrayMixerRed = -10,
	            Shadows2012 = 4,
	            Texture = 4,
	        },
	        bw = true,
	    },
    {
        id = "sony_nostalgic_neg",
        label = "Sony Nostalgic Neg",
        profile = "MindfulLens Sony Nostalgic Neg",
        dcpFile = "AI_KM_SONY_NOSTALGIC_NEG.dcp",
        foundationPreset = "profiles/foundation/sony_nostalgic_neg_foundation.xmp",
        lutFile = "profiles/luts/sony_nostalgic_neg.cube",
        microTune = {
            Contrast2012 = -1,
            HueAdjustmentOrange = 2,
            SaturationAdjustmentOrange = 2,
            SaturationAdjustmentGreen = -2,
            LuminanceAdjustmentOrange = 3,
        },
    },
    {
        id = "classic_cinema",
        label = "Classic Cinema",
        profile = "MindfulLens Classic Cinema",
        dcpFile = "AI_KM_CLASSIC_CINEMA.dcp",
        foundationPreset = "profiles/foundation/classic_cinema_foundation.xmp",
        lutFile = "profiles/luts/classic_cinema.cube",
        microTune = {
            Contrast2012 = -1,
            Clarity2012 = -1,
            SaturationAdjustmentOrange = 2,
            LuminanceAdjustmentOrange = 3,
        },
    },
    {
        id = "oktar",
        label = "Oktar",
        profile = "MindfulLens Oktar",
        dcpFile = "AI_KM_OKTAR.dcp",
        foundationPreset = "profiles/foundation/oktar_foundation.xmp",
        lutFile = "profiles/luts/oktar.cube",
        microTune = {
            SaturationAdjustmentOrange = 2,
            LuminanceAdjustmentOrange = 2,
            ColorGradeBlending = 44,
        },
    },
    {
        id = "zero_mute",
        label = "Zero Mute",
        profile = "MindfulLens Zero Mute",
        dcpFile = "AI_KM_ZERO_MUTE.dcp",
        foundationPreset = "profiles/foundation/zero_mute_foundation.xmp",
        lutFile = "profiles/luts/zero_mute.cube",
        microTune = {
            Contrast2012 = -3,
            Clarity2012 = -2,
            SaturationAdjustmentBlue = -6,
            ColorGradeBalance = -3,
        },
    },
    {
        id = "cinechrome",
        label = "CineChrome",
        profile = "MindfulLens CineChrome",
        dcpFile = "AI_KM_CINECHROME.dcp",
        foundationPreset = "profiles/foundation/cinechrome_foundation.xmp",
        lutFile = "profiles/luts/cinechrome.cube",
        microTune = {
            Contrast2012 = -2,
            HueAdjustmentAqua = 4,
            SaturationAdjustmentGreen = -4,
            SaturationAdjustmentBlue = -4,
            ColorGradeBalance = -6,
        },
    },
    {
        id = "procolor",
        label = "ProColor",
        profile = "MindfulLens ProColor",
        dcpFile = "AI_KM_PROCOLOR.dcp",
        foundationPreset = "profiles/foundation/procolor_foundation.xmp",
        lutFile = "profiles/luts/procolor.cube",
        microTune = {
            Contrast2012 = 1,
            SaturationAdjustmentOrange = 3,
            SaturationAdjustmentYellow = 1,
            LuminanceAdjustmentOrange = 3,
        },
    },
    {
        id = "blue_velvet_cinestill_50d",
        label = "Blue Velvet - CineStill 50D",
        profile = "MindfulLens Blue Velvet - CineStill 50D",
        dcpFile = "AI_KM_BLUE_VELVET_CINESTILL_50D.dcp",
        foundationPreset = "profiles/foundation/blue_velvet_cinestill_50d_foundation.xmp",
        lutFile = "profiles/luts/blue_velvet_cinestill_50d.cube",
        microTune = {
            Contrast2012 = -2,
            HueAdjustmentAqua = 3,
            HueAdjustmentBlue = 6,
            SaturationAdjustmentBlue = 4,
            ColorGradeBalance = -6,
        },
    },
    {
        id = "cinestill_800",
        label = "CineStill 800",
        profile = "MindfulLens CineStill 800",
        dcpFile = "AI_KM_CINESTILL_800.dcp",
        foundationPreset = "profiles/foundation/cinestill_800_foundation.xmp",
        lutFile = "profiles/luts/cinestill_800.cube",
        microTune = {
            Contrast2012 = -1,
            HueAdjustmentAqua = 2,
            SaturationAdjustmentBlue = 3,
            LuminanceAdjustmentOrange = 2,
            ColorGradeShadowsSat = 4,
        },
    },
    {
        id = "cinestill_x",
        label = "CineStill X",
        profile = "MindfulLens CineStill X",
        dcpFile = "AI_KM_CINESTILL_X.dcp",
        foundationPreset = "profiles/foundation/cinestill_x_foundation.xmp",
        lutFile = "profiles/luts/cinestill_x.cube",
        microTune = {
            HueAdjustmentBlue = 8,
            SaturationAdjustmentAqua = 6,
            SaturationAdjustmentBlue = 8,
            ColorGradeShadowsSat = 4,
        },
    },
    {
        id = "chroma_fade",
        label = "Chroma Fade",
        profile = "MindfulLens Chroma Fade",
        dcpFile = "AI_KM_CHROMA_FADE.dcp",
        foundationPreset = "profiles/foundation/chroma_fade_foundation.xmp",
        lutFile = "profiles/luts/chroma_fade.cube",
        microTune = {
            Contrast2012 = -3,
            Clarity2012 = -2,
            SaturationAdjustmentGreen = -4,
            SaturationAdjustmentBlue = -6,
            LuminanceAdjustmentOrange = 4,
        },
    },
    {
        id = "neo_max",
        label = "Neo Max",
        profile = "MindfulLens Neo Max",
        dcpFile = "AI_KM_NEO_MAX.dcp",
        foundationPreset = "profiles/foundation/neo_max_foundation.xmp",
        lutFile = "profiles/luts/neo_max.cube",
        microTune = {
            Contrast2012 = 3,
            Dehaze = 1,
            SaturationAdjustmentBlue = -4,
            ColorGradeBalance = -4,
        },
    },
    {
        id = "midred_infra",
        label = "MidRed Infra",
        profile = "MindfulLens MidRed Infra",
        dcpFile = "AI_KM_MIDRED_INFRA.dcp",
        foundationPreset = "profiles/foundation/midred_infra_foundation.xmp",
        lutFile = "profiles/luts/midred_infra.cube",
        microTune = {
            HueAdjustmentRed = -8,
            SaturationAdjustmentRed = 6,
            SaturationAdjustmentBlue = -8,
            ColorGradeBalance = 3,
        },
    },
    {
        id = "dreamneg",
        label = "DreamNeg",
        profile = "MindfulLens DreamNeg",
        dcpFile = "AI_KM_DREAMNEG.dcp",
        foundationPreset = "profiles/foundation/dreamneg_foundation.xmp",
        lutFile = "profiles/luts/dreamneg.cube",
        microTune = {
            Contrast2012 = -3,
            Clarity2012 = -2,
            SaturationAdjustmentGreen = -3,
            LuminanceAdjustmentOrange = 4,
            ColorGradeHighlightsSat = 1,
        },
    },
    {
        id = "zetra_100",
        label = "Zetra 100",
        profile = "MindfulLens Zetra 100",
        dcpFile = "AI_KM_ZETRA_100.dcp",
        foundationPreset = "profiles/foundation/zetra_100_foundation.xmp",
        lutFile = "profiles/luts/zetra_100.cube",
        microTune = {
            Contrast2012 = 1,
            SaturationAdjustmentOrange = 2,
            ColorGradeBalance = -1,
        },
    },
    {
        id = "rose_spectra",
        label = "Rose Spectra",
        profile = "MindfulLens Rose Spectra",
        dcpFile = "AI_KM_ROSE_SPECTRA.dcp",
        foundationPreset = "profiles/foundation/rose_spectra_foundation.xmp",
        lutFile = "profiles/luts/rose_spectra.cube",
        microTune = {
            SaturationAdjustmentRed = 4,
            SaturationAdjustmentOrange = 3,
            ColorGradeMidtoneSat = 2,
            ColorGradeBalance = 2,
        },
    },
    {
        id = "asteroid_city_kodak_vision_t200_v1",
        label = "Asteroid City - Kodak Vision T200 - V1",
        profile = "MindfulLens Asteroid City - Kodak Vision T200 - V1",
        dcpFile = "AI_KM_ASTEROID_CITY_KODAK_VISION_T200_V1.dcp",
        foundationPreset = "profiles/foundation/asteroid_city_kodak_vision_t200_v1_foundation.xmp",
        lutFile = "profiles/luts/asteroid_city_kodak_vision_t200_v1.cube",
        microTune = {
            Contrast2012 = -2,
            HueAdjustmentBlue = 8,
            SaturationAdjustmentOrange = -2,
            SaturationAdjustmentAqua = 0,
            SaturationAdjustmentBlue = 5,
            LuminanceAdjustmentOrange = 1,
            LuminanceAdjustmentBlue = 1,
        },
    },
    {
        id = "asteroid_city_kodak_vision_t200_v2",
        label = "Asteroid City - Kodak Vision T200 - V2",
        profile = "MindfulLens Asteroid City - Kodak Vision T200 - V2",
        dcpFile = "AI_KM_ASTEROID_CITY_KODAK_VISION_T200_V2.dcp",
        foundationPreset = "profiles/foundation/asteroid_city_kodak_vision_t200_v2_foundation.xmp",
        lutFile = "profiles/luts/asteroid_city_kodak_vision_t200_v2.cube",
        microTune = {
            Contrast2012 = -1,
            HueAdjustmentBlue = 6,
            SaturationAdjustmentBlue = 3,
            LuminanceAdjustmentOrange = 3,
        },
    },
    {
        id = "ayon_200",
        label = "Ayon 200",
        profile = "MindfulLens Ayon 200",
        dcpFile = "AI_KM_AYON_200.dcp",
        foundationPreset = "profiles/foundation/ayon_200_foundation.xmp",
        lutFile = "profiles/luts/ayon_200.cube",
        microTune = {
            Contrast2012 = -2,
            SaturationAdjustmentOrange = -3,
            SaturationAdjustmentYellow = -5,
            SaturationAdjustmentGreen = 0,
            SaturationAdjustmentAqua = -2,
            SaturationAdjustmentBlue = -2,
            LuminanceAdjustmentOrange = 2,
            LuminanceAdjustmentGreen = 0,
            LuminanceAdjustmentBlue = 1,
        },
    },
    {
        id = "phoenix_harman",
        label = "Phoenix Harman",
        profile = "MindfulLens Phoenix Harman",
        dcpFile = "AI_KM_PHOENIX_HARMAN.dcp",
        foundationPreset = "profiles/foundation/phoenix_harman_foundation.xmp",
        lutFile = "profiles/luts/phoenix_harman.cube",
        microTune = {
            Contrast2012 = 3,
            HueAdjustmentGreen = 6,
            SaturationAdjustmentOrange = 4,
            SaturationAdjustmentAqua = 3,
            ColorGradeShadowsSat = 4,
        },
    },
    {
        id = "phenomena",
        label = "Phenomena",
        profile = "MindfulLens Phenomena",
        dcpFile = "AI_KM_PHENOMENA.dcp",
        foundationPreset = "profiles/foundation/phenomena_foundation.xmp",
        lutFile = "profiles/luts/phenomena.cube",
        microTune = {
            Contrast2012 = 2,
            SaturationAdjustmentOrange = 2,
            ColorGradeBalance = 0,
        },
    },
    {
        id = "crimson",
        label = "Crimson",
        profile = "MindfulLens Crimson",
        dcpFile = "AI_KM_CRIMSON.dcp",
        foundationPreset = "profiles/foundation/crimson_foundation.xmp",
        lutFile = "profiles/luts/crimson.cube",
        microTune = {
            SaturationAdjustmentRed = 6,
            SaturationAdjustmentOrange = 3,
            ColorGradeMidtoneSat = 3,
            ColorGradeBalance = 3,
        },
    },
    {
        id = "acidnom",
        label = "Acidnom",
        profile = "MindfulLens Acidnom",
        dcpFile = "AI_KM_ACIDNOM.dcp",
        foundationPreset = "profiles/foundation/acidnom_foundation.xmp",
        lutFile = "profiles/luts/acidnom.cube",
        microTune = {
            HueAdjustmentGreen = 8,
            HueAdjustmentAqua = 6,
            SaturationAdjustmentGreen = 4,
            ColorGradeBalance = -4,
        },
    },
    {
        id = "estra_500",
        label = "Estra 500",
        profile = "MindfulLens Estra 500",
        dcpFile = "AI_KM_ESTRA_500.dcp",
        foundationPreset = "profiles/foundation/estra_500_foundation.xmp",
        lutFile = "profiles/luts/estra_500.cube",
        microTune = {
            Contrast2012 = -1,
            SaturationAdjustmentOrange = 1,
            LuminanceAdjustmentOrange = 3,
            ColorGradeBalance = -2,
        },
    },
    {
        id = "x_tarr",
        label = "X-Tarr",
        profile = "MindfulLens X-Tarr",
        dcpFile = "AI_KM_X_TARR.dcp",
        foundationPreset = "profiles/foundation/x_tarr_foundation.xmp",
        lutFile = "profiles/luts/x_tarr.cube",
        microTune = {
            HueAdjustmentYellow = -6,
            SaturationAdjustmentGreen = 3,
            SaturationAdjustmentBlue = 2,
            ColorGradeBalance = -1,
        },
    },
    {
        id = "magic_spice",
        label = "Magic Spice",
        profile = "MindfulLens Magic Spice",
        dcpFile = "AI_KM_MAGIC_SPICE.dcp",
        foundationPreset = "profiles/foundation/magic_spice_foundation.xmp",
        lutFile = "profiles/luts/magic_spice.cube",
        microTune = {
            SaturationAdjustmentOrange = 5,
            SaturationAdjustmentYellow = 2,
            LuminanceAdjustmentOrange = 4,
            ColorGradeBalance = 3,
        },
    },
    {
        id = "amarelo_30d",
        label = "Amarelo 30D",
        profile = "MindfulLens Amarelo 30D",
        dcpFile = "AI_KM_AMARELO_30D.dcp",
        foundationPreset = "profiles/foundation/amarelo_30d_foundation.xmp",
        lutFile = "profiles/luts/amarelo_30d.cube",
        microTune = {
            SaturationAdjustmentOrange = 4,
            SaturationAdjustmentYellow = 3,
            LuminanceAdjustmentYellow = 4,
            ColorGradeBalance = 4,
        },
    },
    {
        id = "vespera",
        label = "Vespera",
        profile = "MindfulLens Vespera",
        dcpFile = "AI_KM_VESPERA.dcp",
        foundationPreset = "profiles/foundation/vespera_foundation.xmp",
        lutFile = "profiles/luts/vespera.cube",
        microTune = {
            Contrast2012 = 2,
            SaturationAdjustmentBlue = 2,
            ColorGradeBalance = -2,
        },
    },
    {
        id = "veniliqum",
        label = "Veniliqum",
        profile = "MindfulLens Veniliqum",
        dcpFile = "AI_KM_VENILIQUM.dcp",
        foundationPreset = "profiles/foundation/veniliqum_foundation.xmp",
        lutFile = "profiles/luts/veniliqum.cube",
        microTune = {
            HueAdjustmentBlue = 5,
            SaturationAdjustmentBlue = 3,
            ColorGradeMidtoneHue = 320,
            ColorGradeBalance = -2,
        },
    },
    {
        id = "gold_luxe",
        label = "Gold Luxe",
        profile = "MindfulLens Gold Luxe",
        dcpFile = "AI_KM_GOLD_LUXE.dcp",
        foundationPreset = "profiles/foundation/gold_luxe_foundation.xmp",
        lutFile = "profiles/luts/gold_luxe.cube",
        microTune = {
            Contrast2012 = -1,
            Clarity2012 = -1,
            SaturationAdjustmentOrange = 5,
            SaturationAdjustmentYellow = 2,
            LuminanceAdjustmentOrange = 4,
        },
    },
    {
        id = "fuji_400h_cc",
        label = "Fuji 400H",
        profile = "MindfulLens Fuji 400H",
        dcpFile = "AI_KM_FUJI_400H_CC.dcp",
        foundationPreset = "profiles/foundation/fuji_400h_foundation.xmp",
        lutFile = "profiles/luts/fuji_400h_cc.cube",
    },
    {
        id = "ektar_100_cc",
        label = "Ektar 100",
        profile = "MindfulLens Ektar 100",
        dcpFile = "AI_KM_EKTAR_100_CC.dcp",
        foundationPreset = "profiles/foundation/ektar_100_foundation.xmp",
        lutFile = "profiles/luts/ektar_100_cc.cube",
    },
    {
        id = "kodak_color_plus_200_cc",
        label = "Kodak Color Plus 200",
        profile = "MindfulLens Kodak Color Plus 200",
        dcpFile = "AI_KM_KODAK_COLOR_PLUS_200_CC.dcp",
        foundationPreset = "profiles/foundation/colorplus_200_foundation.xmp",
        lutFile = "profiles/luts/kodak_color_plus_200_cc.cube",
    },
    {
        id = "ektachrome_cc",
        label = "Ektachrome",
        profile = "MindfulLens Ektachrome",
        dcpFile = "AI_KM_EKTACHROME_CC.dcp",
        foundationPreset = "profiles/foundation/ektachrome_foundation.xmp",
        lutFile = "profiles/luts/ektachrome_cc.cube",
    },
    {
        id = "fuji_provia_cc",
        label = "Fuji Provia",
        profile = "MindfulLens Fuji Provia",
        dcpFile = "AI_KM_FUJI_PROVIA_CC.dcp",
        foundationPreset = "profiles/foundation/fuji_provia_100f_foundation.xmp",
        lutFile = "profiles/luts/fuji_provia_cc.cube",
    },
    {
        id = "provia_rx_cc",
        label = "Provia RX",
        profile = "MindfulLens Provia RX",
        dcpFile = "AI_KM_PROVIA_RX_CC.dcp",
        foundationPreset = "profiles/foundation/fuji_provia_rx_foundation.xmp",
        lutFile = "profiles/luts/provia_rx_cc.cube",
    },
    {
        id = "astia_cc",
        label = "Astia",
        profile = "MindfulLens Astia",
        dcpFile = "AI_KM_ASTIA_CC.dcp",
        foundationPreset = "profiles/foundation/fuji_astia_100f_foundation.xmp",
        lutFile = "profiles/luts/astia_cc.cube",
    },
    {
        id = "fortia_50_cc",
        label = "Fortia 50",
        profile = "MindfulLens Fortia 50",
        dcpFile = "AI_KM_FORTIA_50_CC.dcp",
        foundationPreset = "profiles/foundation/fuji_fortia_50_foundation.xmp",
        lutFile = "profiles/luts/fortia_50_cc.cube",
    },
    {
        id = "tmax100_cc",
        label = "T-Max100",
        profile = "MindfulLens T-Max100",
        dcpFile = "AI_KM_TMAX100_CC.dcp",
        foundationPreset = "profiles/foundation/bw_tmax_100_foundation.xmp",
        lutFile = "profiles/luts/tmax100_cc.cube",
        bw = true,
    },
    {
        id = "delta_3200_cc",
        label = "Delta 3200",
        profile = "MindfulLens Delta 3200",
        dcpFile = "AI_KM_DELTA_3200_CC.dcp",
        foundationPreset = "profiles/foundation/bw_delta_3200_foundation.xmp",
        lutFile = "profiles/luts/delta_3200_cc.cube",
        bw = true,
    },
    {
        id = "ilford_hp5_cc",
        label = "Ilford HP5",
        profile = "MindfulLens Ilford HP5",
        dcpFile = "AI_KM_ILFORD_HP5_CC.dcp",
        foundationPreset = "profiles/foundation/bw_hp5_foundation.xmp",
        lutFile = "profiles/luts/ilford_hp5_cc.cube",
        bw = true,
    },
    {
        id = "redscale_ultra_cc",
        label = "RedScale Ultra",
        profile = "MindfulLens RedScale Ultra",
        dcpFile = "AI_KM_REDSCALE_ULTRA_CC.dcp",
        foundationPreset = "profiles/foundation/redscale_ultra_foundation.xmp",
        lutFile = "profiles/luts/redscale_ultra_cc.cube",
    },
    {
        id = "solara_100_cc",
        label = "Solara 100",
        profile = "MindfulLens Solara 100",
        dcpFile = "AI_KM_SOLARA_100_CC.dcp",
        foundationPreset = "profiles/foundation/kodak_solara_100_foundation.xmp",
        lutFile = "profiles/luts/solara_100_cc.cube",
    },
}
M.formats = {
    { id = "35mm", label = "35mm | maly obrazek" },
    { id = "mf_120", label = "120 | sredni format" },
    { id = "lf_4x5", label = "4x5 | duzy format" },
    { id = "lf_8x10", label = "8x10 | wielki format" },
}

M.sourceScales = {
    { id = "auto", label = "Auto (wykryj aparat)" },
    { id = "full_frame", label = "Pelna klatka" },
    { id = "aps_c", label = "APS-C" },
    { id = "micro_four_thirds", label = "Micro 4/3" },
    { id = "compact_small", label = "Mala matryca / kompakt" },
    { id = "digital_mf", label = "Cyfrowy sredni format" },
}

M.profileModes = {
    { id = "production", label = "Production (v1 locked)" },
    { id = "debug", label = "Debug (strong split)" },
}

M.nightBoostLevels = {
    { id = "off", label = "Off" },
    { id = "soft", label = "Soft" },
    { id = "medium", label = "Medium" },
    { id = "strong", label = "Strong" },
}

M.modularPresets = {
    {
        id = "print_kodak_2383_soft",
        label = "Print Media | Kodak 2383 Soft",
        xmpFile = "profiles/modular/print/print_kodak_2383_soft.xmp",
    },
    {
        id = "print_kodak_endura_warm",
        label = "Print Media | Kodak Endura Warm",
        xmpFile = "profiles/modular/print/print_kodak_endura_warm.xmp",
    },
    {
        id = "print_fuji_crystal_clean",
        label = "Print Media | Fuji Crystal Clean",
        xmpFile = "profiles/modular/print/print_fuji_crystal_clean.xmp",
    },
    {
        id = "halation_soft",
        label = "Optics | Halation Soft",
        xmpFile = "profiles/modular/optics/halation_soft.xmp",
    },
    {
        id = "halation_strong",
        label = "Optics | Halation Strong",
        xmpFile = "profiles/modular/optics/halation_strong.xmp",
    },
    {
        id = "bloom_soft",
        label = "Optics | Bloom Soft",
        xmpFile = "profiles/modular/optics/bloom_soft.xmp",
    },
    {
        id = "grain_35mm_soft",
        label = "Grain | 35mm Soft",
        xmpFile = "profiles/modular/grain/grain_35mm_soft.xmp",
    },
    {
        id = "grain_35mm_rough",
        label = "Grain | 35mm Rough",
        xmpFile = "profiles/modular/grain/grain_35mm_rough.xmp",
    },
    {
        id = "grain_120_clean",
        label = "Grain | 120 Clean",
        xmpFile = "profiles/modular/grain/grain_120_clean.xmp",
    },
    {
        id = "prep_defringe_soft",
        label = "Prep | Defringe Soft",
        xmpFile = "profiles/modular/prep/prep_defringe_soft.xmp",
    },
    {
        id = "prep_defringe_strong",
        label = "Prep | Defringe Strong",
        xmpFile = "profiles/modular/prep/prep_defringe_strong.xmp",
    },
}

M.cameraFallbacks = {
    ["OLYMPUS EP-1"] = "OLYMPUS E-M1 Mark II",
    ["OLYMPUS E-P1"] = "OLYMPUS E-M1 Mark II",
    ["SONY A9"] = "SONY A9 II",
    ["LEICA M9"] = "LEICA M10",
}

M.defaultEmulsionId = "portra_400"
M.defaultFormatId = "35mm"
M.defaultSourceScaleId = "auto"
M.defaultProfileMode = "production"
M.defaultConversionMode = "analyze"
M.defaultColorProcess = "refined"
M.defaultNightBoostLevel = "off"
M.defaultAutoDmin = true
M.defaultApplyFoundation = true
M.defaultUseAnalyzerWB = true
M.defaultUseAnalyzerOverrides = false
M.defaultApplyCameraProfile = false
M.defaultEnableBackupRender = false
M.defaultBackupOnProfileReject = true
M.defaultAllowGenericFallback = false
M.defaultDebugKeepTemp = false
M.defaultLutIntensity = 100
M.defaultSaturationTrim = 0
M.defaultLabGlow = 0
M.defaultLabFade = 0
M.defaultSoftHighs = false
M.defaultSoftLows = false
M.defaultWhiteClip = 0
M.defaultBlackClip = 0
M.defaultMatchMode = "full"
M.publicCatalogVersion = publicCatalog.catalogVersion
M.publicCatalogCodename = publicCatalog.catalogCodename

for _, em in ipairs(M.emulsions) do
    em.legacyLabel = em.label
    em.publicLabel = publicCatalog.getPublicLabel(em.id, em.label)
    em.clientFacingLabel = publicCatalog.getClientFacingLabel(em.id, em.legacyLabel, em.publicLabel)
    em.publicCategoryId = publicCatalog.getCategoryId(em.id, em.type, em.bw == true)
    em.publicCategoryMeta = publicCatalog.getCategoryMeta(em.publicCategoryId)
    em.publicCategoryTitle = tostring((em.publicCategoryMeta and em.publicCategoryMeta.title) or "")
    em.publicCategoryDescription = tostring((em.publicCategoryMeta and em.publicCategoryMeta.short) or "")
    em.publicTags = publicCatalog.getTags(em.id, em.type, em.bw == true)
end

function M.findEmulsion(emulsionId)
    for _, em in ipairs(M.emulsions) do
        if em.id == emulsionId then
            return em
        end
    end
    return nil
end

function M.getModularPresetCount()
    return #(M.modularPresets or {})
end

return M
