import { filmStocks } from '../engine/filmProfiles.js';
import { getPointerCoordinates } from './getPointerCoordinates.js';
import { bumpDevelopCatalogLoadFromNonCatalogSource } from './filmLabDevelopCatalogLoadCooperation.js';
import { buildCanvasViewportDebugAndCurveWorkbenchShellOverlayArgs } from './filmLabFilmLabProBuildCanvasViewportDebugCurveShellArgs.js';

/**
 * Argument factories for useFilmLabWorkbenchChromeCaptureFilmCropStraightenPanelAndCanvasViewportDebugCurveShellCluster (Film Lab Pro).
 */
export const filmLabFilmLabProClusterArgFactories = {
  buildChromeCatalogViewportArgs: (w) => ({
    chromeCatalogEngineArgs: {
      chromeLayoutStraightenArgs: {
        shellRef: w.shellRef,
        leftSidebarRef: w.leftSidebarRef,
        rightSidebarRef: w.rightSidebarRef,
        toolbarRef: w.toolbarRef,
        workspaceFooterRef: w.workspaceFooterRef,
        canvasAreaRef: w.canvasAreaRef,
        canvasCenterRef: w.canvasCenterRef,
        canvasStageRef: w.canvasStageRef,
        imageUrl: w.imageUrl,
        uploadedFile: w.uploadedFile,
        viewMode: w.viewMode,
        cropLiveRectRef: w.cropLiveRectRef,
        cropLiveRect: w.cropLiveRect,
        straightenGuideRef: w.straightenGuideRef,
        straightenGuide: w.straightenGuide,
      },
      catalogCropGeometryEngineSidecarArgs: {
        catalogEngineCropGeometryArgs: {
          filmCatalogArgs: {
            activeFilmIndex: w.activeFilmIndex,
            searchQuery: w.searchQuery,
            activeCategory: w.activeCategory,
          },
          engineAdjustmentsArgs: {
            activePanel: w.activePanel,
            adjustments: w.adjustments,
            userCurves: w.userCurves,
            colorMixer: w.colorMixer,
            colorGrading: w.colorGrading,
            colorCalibration: w.colorCalibration,
            isAdjusting: w.isAdjusting,
            interactionKind: w.interactionKind,
          },
          cropDerivedGeometryArgs: {
            adjustments: w.adjustments,
            cropLiveRect: w.cropLiveRect,
            straightenGuide: w.straightenGuide,
          },
        },
        engineSidecarArgs: {
          imageUrl: w.imageUrl,
          uploadedFile: w.uploadedFile,
          activeFilmIndex: w.activeFilmIndex,
          rawBackendPreference: w.rawBackendPreference,
          rawBackendMode: w.rawBackendMode,
          rawLinearStageOverride: w.rawLinearStageOverride,
          rawLinearStageMode: w.rawLinearStageMode,
          zoomMode: w.zoomMode,
          metadataViewMode: w.metadataViewMode,
          setMetadataViewMode: w.setMetadataViewMode,
          exifMeta: w.exifMeta,
          zoom: w.zoom,
          panOffset: w.panOffset,
          adjustments: w.adjustments,
          colorCalibration: w.colorCalibration,
          colorGrading: w.colorGrading,
          colorMixer: w.colorMixer,
          interactionKind: w.interactionKind,
          isAdjusting: w.isAdjusting,
          isPanning: w.isPanning,
          userCurves: w.userCurves,
          curveInteractionLiveRef: w.curveInteractionLiveRef,
        },
      },
    },
    viewportRefsPreviewSprocketArgs: {
      zoomRef: w.zoomRef,
      zoom: w.zoom,
      panOffsetRef: w.panOffsetRef,
      panOffset: w.panOffset,
      panDragRef: w.panDragRef,
      setZoom: w.setZoom,
      setPanOffset: w.setPanOffset,
      setIsPanning: w.setIsPanning,
      histogramCanvasRef: w.histogramCanvasRef,
      isAdjusting: w.isAdjusting,
      interactionKind: w.interactionKind,
      curvesCanvasRef: w.curvesCanvasRef,
      userCurves: w.userCurves,
      activeCurveCh: w.activeCurveCh,
      activePanel: w.activePanel,
      uploadedFile: w.uploadedFile,
      imageUrl: w.imageUrl,
      setExifMeta: w.setExifMeta,
      adjustmentsFrame: w.adjustments.frame,
      setAdjustments: w.setAdjustments,
    },
  }),
  buildCaptureUploadUndoWorkbenchClipboardArgs: (b) => ({
    captureAndUploadRestoreArgs: {
      captureArgs: {
        activeFilmIndex: b.activeFilmIndex,
        adjustments: b.adjustments,
        userCurves: b.userCurves,
        zoomRef: b.zoomRef,
        panOffsetRef: b.panOffsetRef,
        colorMixer: b.colorMixer,
        colorGrading: b.colorGrading,
        colorCalibration: b.colorCalibration,
        uploadedFile: b.uploadedFile,
      },
      uploadRestoreArgs: {
        restoreSnapshotRef: b.restoreSnapshotRef,
        onBeforeApplyUploadedSource: bumpDevelopCatalogLoadFromNonCatalogSource,
        activePanel: b.activePanel,
        setUploadedFile: b.setUploadedFile,
        setImageUrl: b.setImageUrl,
        setActivePanel: b.setActivePanel,
        setZoomMode: b.setZoomMode,
        setPreferFullResPreview: b.setPreferFullResPreview,
        zoomRef: b.zoomRef,
        panOffsetRef: b.panOffsetRef,
        setZoom: b.setZoom,
        setPanOffset: b.setPanOffset,
        setAdjustments: b.setAdjustments,
        setActiveFilmIndex: b.setActiveFilmIndex,
        setUserCurves: b.setUserCurves,
        setColorMixer: b.setColorMixer,
        setColorGrading: b.setColorGrading,
        setColorCalibration: b.setColorCalibration,
      },
    },
    undoSliderWorkbenchAutoDevelopArgs: {
      undoHistoryClusterArgs: {
        undoRedoArgs: {
          setHistoryRevision: b.setHistoryRevision,
        },
        historyTimelineArgs: {
          filmStocks,
          activeFilmIndex: b.activeFilmIndex,
          adjustments: b.adjustments,
          historyRevision: b.historyRevision,
          zoom: b.zoom,
        },
      },
      sliderWorkbenchArgs: {
        interactionReleaseTimeoutRef: b.interactionReleaseTimeoutRef,
        sliderDragActivationRef: b.sliderDragActivationRef,
        clearSliderReleaseFailsafe: b.clearSliderReleaseFailsafe,
        stopSliderDragActivationTracking: b.stopSliderDragActivationTracking,
        scheduleSliderReleaseFailsafe: b.scheduleSliderReleaseFailsafe,
        activateSliderDragIfNeeded: b.activateSliderDragIfNeeded,
        setAdjustments: b.setAdjustments,
        adjustments: b.adjustments,
        isAdjusting: b.isAdjusting,
        setIsAdjusting: b.setIsAdjusting,
        setInteractionKind: b.setInteractionKind,
        activeFilm: b.activeFilm,
        isInputProfile: b.isInputProfile,
      },
      workbenchUndoAwareArgs: {
        activeFilm: b.activeFilm,
        activeCurveCh: b.activeCurveCh,
        filmStocks,
        setActiveFilmIndex: b.setActiveFilmIndex,
        setAdjustments: b.setAdjustments,
        setUserCurves: b.setUserCurves,
        setColorMixer: b.setColorMixer,
        setColorGrading: b.setColorGrading,
        setColorCalibration: b.setColorCalibration,
        setPreferFullResPreview: b.setPreferFullResPreview,
        zoomRef: b.zoomRef,
        panOffsetRef: b.panOffsetRef,
        setZoom: b.setZoom,
        setPanOffset: b.setPanOffset,
      },
      colorGradeLiveArgs: {
        setColorMixer: b.setColorMixer,
        setColorGrading: b.setColorGrading,
        setColorCalibration: b.setColorCalibration,
      },
      autoDevelopArgs: {
        canvasRef: b.canvasRef,
        hasImage: b.hasImage,
        adjustments: b.adjustments,
        pipelineInfo: b.pipelineInfo,
        renderDebugInfo: b.renderDebugInfo,
        setAdjustments: b.setAdjustments,
      },
    },
    clipboardSessionClusterArgs: {
      editClipboardArgs: {
        activeFilmIndex: b.activeFilmIndex,
        activeFilm: b.activeFilm,
        adjustments: b.adjustments,
        userCurves: b.userCurves,
        colorMixer: b.colorMixer,
        colorGrading: b.colorGrading,
        colorCalibration: b.colorCalibration,
        zoom: b.zoom,
        panOffset: b.panOffset,
        filmStocks,
        setAdjustments: b.setAdjustments,
        setUserCurves: b.setUserCurves,
        setActiveFilmIndex: b.setActiveFilmIndex,
        setColorMixer: b.setColorMixer,
        setColorGrading: b.setColorGrading,
        setColorCalibration: b.setColorCalibration,
        setClipboardFeedback: b.setClipboardFeedback,
      },
      sessionPersistenceArgs: {
        sessionPersistTimerRef: b.sessionPersistTimerRef,
        skipNextPersistRef: b.skipNextPersistRef,
        cropLiveRectRef: b.cropLiveRectRef,
        pendingAutosavePayloadRef: b.pendingAutosavePayloadRef,
        setActiveCategory: b.setActiveCategory,
        setSearchQuery: b.setSearchQuery,
        setActiveCurveCh: b.setActiveCurveCh,
        setStraightenGuide: b.setStraightenGuide,
        setCropLiveRect: b.setCropLiveRect,
        setRawBackendMode: b.setRawBackendMode,
        setRawLinearStageMode: b.setRawLinearStageMode,
        setSessionRestoreNotice: b.setSessionRestoreNotice,
        setSessionRestorePrompt: b.setSessionRestorePrompt,
        activeFilmIndex: b.activeFilmIndex,
        adjustments: b.adjustments,
        userCurves: b.userCurves,
        colorMixer: b.colorMixer,
        colorGrading: b.colorGrading,
        colorCalibration: b.colorCalibration,
        zoom: b.zoom,
        panOffset: b.panOffset,
        activePanel: b.activePanel,
        activeCategory: b.activeCategory,
        searchQuery: b.searchQuery,
        activeCurveCh: b.activeCurveCh,
        straightenGuide: b.straightenGuide,
        cropLiveRect: b.cropLiveRect,
        rawBackendMode: b.rawBackendMode,
        rawLinearStageMode: b.rawLinearStageMode,
        uploadedFile: b.uploadedFile,
        hasImage: b.hasImage,
      },
    },
    recipeDebugKeyboardArgs: { showRenderDebugPanel: b.showRenderDebugPanel },
  }),
  buildFilmViewCropStraightenPanelArgs: (c) => ({
    filmViewCropRectApplyAndDragLayoutArgs: {
      filmViewAndCropRectApplyArgs: {
        saveUndo: c.saveUndo,
        filmStocks,
        setActiveFilmIndex: c.setActiveFilmIndex,
        setAdjustments: c.setAdjustments,
        hasImage: c.hasImage,
        activeCropOverlayMode: c.activeCropOverlayMode,
        activeCropAspectPreset: c.activeCropAspectPreset,
        imageMeta: c.imageMeta,
        exifMeta: c.exifMeta,
        adjustmentsRotation: c.adjustments?.rotation,
        activeCropRectNorm: c.activeCropRectNorm,
        cropLiveRectRef: c.cropLiveRectRef,
        setCropLiveRect: c.setCropLiveRect,
        cropLiveRect: c.cropLiveRect,
        activeCropAspect: c.activeCropAspect,
        cropRectNorm: c.cropRectNorm,
      },
      cropDragAndLayoutEffectsArgs: {
        cropDragStateRef: c.cropDragStateRef,
        cropDragPendingPointRef: c.cropDragPendingPointRef,
        cropDragFrameRef: c.cropDragFrameRef,
        cropOverlayInteractionRef: c.cropOverlayInteractionRef,
        cropLiveRectRef: c.cropLiveRectRef,
        getPointerCoordinates,
        setInteractionKind: c.setInteractionKind,
        setIsAdjusting: c.setIsAdjusting,
        setCropLiveRect: c.setCropLiveRect,
        hasImage: c.hasImage,
        activePanel: c.activePanel,
        isStraightenToolArmed: c.isStraightenToolArmed,
        cropAspectRatio: c.activeCropAspect?.ratio,
        activeCropAspectPreset: c.activeCropAspectPreset,
        adjustmentsRotation: c.adjustments?.rotation,
        imageMeta: c.imageMeta,
        exifMeta: c.exifMeta,
        activeCropRectNorm: c.activeCropRectNorm,
        cropRectNorm: c.cropRectNorm,
        saveUndo: c.saveUndo,
        lastNonCropPanelRef: c.lastNonCropPanelRef,
        setActivePanel: c.setActivePanel,
        lastCropGeometryKeyRef: c.lastCropGeometryKeyRef,
      },
    },
    straightenPanelArgs: {
      straightenDragOutsideCropArgs: {
        straightenGuideRef: c.straightenGuideRef,
        straightenSessionSnapshotRef: c.straightenSessionSnapshotRef,
        straightenSessionLevelRef: c.straightenSessionLevelRef,
        straightenHasMeaningfulChangeRef: c.straightenHasMeaningfulChangeRef,
        straightenDragStateRef: c.straightenDragStateRef,
        straightenDragPendingPointRef: c.straightenDragPendingPointRef,
        straightenDragFrameRef: c.straightenDragFrameRef,
        cropOverlayInteractionRef: c.cropOverlayInteractionRef,
        canvasRef: c.canvasRef,
        activeCropRectNorm: c.activeCropRectNorm,
        setStraightenGuide: c.setStraightenGuide,
        setInteractionKind: c.setInteractionKind,
        setIsAdjusting: c.setIsAdjusting,
        setIsStraightenToolArmed: c.setIsStraightenToolArmed,
        setAdjustments: c.setAdjustments,
        captureCurrentSnapshot: c.captureCurrentSnapshot,
        pushUndoSnapshot: c.pushUndoSnapshot,
        hasImage: c.hasImage,
        activePanel: c.activePanel,
        isStraightenToolArmed: c.isStraightenToolArmed,
        adjustmentsLevel: c.adjustments?.level,
        saveUndo: c.saveUndo,
      },
      panelNavigationArgs: {
        activePanel: c.activePanel,
        lastNonCropPanelRef: c.lastNonCropPanelRef,
        setActivePanel: c.setActivePanel,
      },
      studioWorkspaceArgs: {
        setStudioWorkspace: c.setStudioWorkspace,
        setActivePanel: c.setActivePanel,
        setIsExportModalOpen: c.setIsExportModalOpen,
        studioWorkspace: c.studioWorkspace,
        uiMode: c.adjustments?.uiMode,
      },
    },
  }),
  buildCanvasViewportDebugAndCurveWorkbenchShellOverlayArgs,
};
