import { clamp } from './crop/cropStraighten.js';
import { SLIDER_DEFS } from './workbenchConstants.js';

/**
 * `buildCanvasViewportDebugAndCurveWorkbenchShellOverlayArgs` for Film Lab Pro workbench cluster.
 */
export function buildCanvasViewportDebugAndCurveWorkbenchShellOverlayArgs(d) {
  return {
    canvasViewportWithDebugArgs: {
      canvasViewportIdentityOverlayArgs: {
        uploadedFile: d.uploadedFile,
        imageMeta: d.imageMeta,
        adjustments: d.adjustments,
        activePanel: d.activePanel,
        exifMeta: d.exifMeta,
        hasImage: d.hasImage,
        devicePixelRatio: d.devicePixelRatio,
        chromeBox: d.chromeBox,
        canvasAreaRef: d.canvasAreaRef,
        canvasStageRef: d.canvasStageRef,
        canvasCenterRef: d.canvasCenterRef,
        canvasStageSize: d.canvasStageSize,
        zoom: d.zoom,
        setZoom: d.setZoom,
        panOffset: d.panOffset,
        setPanOffset: d.setPanOffset,
        zoomRef: d.zoomRef,
        panOffsetRef: d.panOffsetRef,
        zoomAnchorRef: d.zoomAnchorRef,
        panDragRef: d.panDragRef,
        setIsPanning: d.setIsPanning,
        setPreferFullResPreview: d.setPreferFullResPreview,
        setZoomMode: d.setZoomMode,
        isStraightenToolArmed: d.isStraightenToolArmed,
        acceptCropDraft: d.acceptCropDraft,
        acceptManualStraighten: d.acceptManualStraighten,
        lastAutoFitKeyRef: d.lastAutoFitKeyRef,
      },
      viewportDebugKeydownUnmountArgs: {
        viewportDebugStateArgs: {
          zoom: d.zoom,
          devicePixelRatio: d.devicePixelRatio,
          panOffsetRef: d.panOffsetRef,
        },
        shellGlobalKeydownArgs: {
          activePanel: d.activePanel,
          studioWorkspace: d.studioWorkspace,
          hasImage: d.hasImage,
          hasActiveSource: d.hasActiveSource,
          setIsExportModalOpen: d.setIsExportModalOpen,
          isStraightenToolArmed: d.isStraightenToolArmed,
          isPreviewFullMode: d.isPreviewFullMode,
          showRenderDebugPanel: d.showRenderDebugPanel,
          zoomRef: d.zoomRef,
          acceptCropDraft: d.acceptCropDraft,
          acceptManualStraighten: d.acceptManualStraighten,
          cancelManualStraighten: d.cancelManualStraighten,
          setAdjustments: d.setAdjustments,
          setIsPreviewFullMode: d.setIsPreviewFullMode,
          setIsShortcutHelpOpen: d.setIsShortcutHelpOpen,
          togglePreviewFullMode: d.togglePreviewFullMode,
          setIsMetadataPanelOpen: d.setIsMetadataPanelOpen,
          cycleMetadataViewMode: d.cycleMetadataViewMode,
          cycleRawLinearStageMode: d.cycleRawLinearStageMode,
          cycleCropOverlayMode: d.cycleCropOverlayMode,
          rotateCropOverlay: d.rotateCropOverlay,
          applyAutoExposure: d.applyAutoExposure,
          applyAutoColor: d.applyAutoColor,
          triggerDustZip: d.triggerDustZip,
          triggerRawLeakZip: d.triggerRawLeakZip,
          handleToolbarUndo: d.handleToolbarUndo,
          handleToolbarRedo: d.handleToolbarRedo,
          undoStackRef: d.undoStackRef,
          redoStackRef: d.redoStackRef,
        },
        unmountCleanupArgs: {
          interactionReleaseTimeoutRef: d.interactionReleaseTimeoutRef,
          sliderReleaseFailsafeTimeoutRef: d.sliderReleaseFailsafeTimeoutRef,
          stopSliderDragActivationTracking: d.stopSliderDragActivationTracking,
          sliderUpdateFrameRef: d.sliderUpdateFrameRef,
          pendingSliderUpdatesRef: d.pendingSliderUpdatesRef,
          panDragRef: d.panDragRef,
          stopStraightenDrag: d.stopStraightenDrag,
        },
      },
    },
    curveWorkbenchShellOverlayArgs: {
      curveWorkbenchFirstProps: {
        activePanel: d.activePanel,
        curvesCanvasRef: d.curvesCanvasRef,
        activeCurveCh: d.activeCurveCh,
        userCurves: d.userCurves,
        saveUndo: d.saveUndo,
        interactionReleaseTimeoutRef: d.interactionReleaseTimeoutRef,
        clearSliderReleaseFailsafe: d.clearSliderReleaseFailsafe,
        setIsAdjusting: d.setIsAdjusting,
        setInteractionKind: d.setInteractionKind,
        setUserCurves: d.setUserCurves,
        handleSliderEnd: d.handleSliderEnd,
        clamp,
        curveInteractionLiveRef: d.curveInteractionLiveRef,
        requestCurvePreviewFrame: d.requestCurvePreviewFrame,
      },
      curveWorkbenchSecondProps: {
        adjustments: d.adjustments,
        updateAdjustment: d.updateAdjustment,
        isInputProfile: d.isInputProfile,
        sliderDefs: SLIDER_DEFS,
        handleSliderStart: d.handleSliderStart,
        handleSliderEnd: d.handleSliderEnd,
        handleSliderChange: d.handleSliderChange,
        handleTemperatureSliderChange: d.handleTemperatureSliderChange,
        handleSliderDoubleClick: d.handleSliderDoubleClick,
        handleSliderTouchStart: d.handleSliderTouchStart,
        handleCustomSliderTouchStart: d.handleCustomSliderTouchStart,
        sliderDragActivationRef: d.sliderDragActivationRef,
        isAdjusting: d.isAdjusting,
        scheduleSliderReleaseFailsafe: d.scheduleSliderReleaseFailsafe,
        setInteractionKind: d.setInteractionKind,
        setIsAdjusting: d.setIsAdjusting,
        queueSliderUpdate: d.queueSliderUpdate,
      },
      shellOverlayPropsArgs: {
        adjustments: d.adjustments,
        imageMeta: d.imageMeta,
        hasImage: d.hasImage,
        uploadedFile: d.uploadedFile,
        cropMaskPath: d.cropMaskPath,
        cropRectPercent: d.cropRectPercent,
        activeCropOverlayMode: d.activeCropOverlayMode,
        activeCropOverlayOrientation: d.activeCropOverlayOrientation,
        cropGuideTransform: d.cropGuideTransform,
        cropOverlayGuideElements: d.cropOverlayGuideElements,
        isStraightenToolArmed: d.isStraightenToolArmed,
        handleStraightenPointerDown: d.handleStraightenPointerDown,
        straightenGuidePercent: d.straightenGuidePercent,
        cropOverlayInteractionRef: d.cropOverlayInteractionRef,
        acceptManualStraighten: d.acceptManualStraighten,
        handleCropOverlayDoubleClick: d.handleCropOverlayDoubleClick,
        handleStraightenPointerMove: d.handleStraightenPointerMove,
        handleStraightenPointerUp: d.handleStraightenPointerUp,
        handleStraightenPointerCancel: d.handleStraightenPointerCancel,
        handleCropPointerMove: d.handleCropPointerMove,
        handleCropPointerUp: d.handleCropPointerUp,
        handleCropPointerCancel: d.handleCropPointerCancel,
        cropMoveZoneRect: d.cropMoveZoneRect,
        cropHandles: d.cropHandles,
        cropHandleHitboxes: d.cropHandleHitboxes,
        handleCropHandlePointerDown: d.handleCropHandlePointerDown,
        hasPendingCropChanges: d.hasPendingCropChanges,
        acceptCropDraft: d.acceptCropDraft,
        showRenderDebugPanel: d.showRenderDebugPanel,
        exportDebugReport: d.exportDebugReport,
        exportRecipeSidecar: d.exportRecipeSidecar,
        copyRecipeDocumentJson: d.copyRecipeDocumentJson,
        debugExportFeedback: d.debugExportFeedback,
        recipeExportFeedback: d.recipeExportFeedback,
        recipeClipboardFeedback: d.recipeClipboardFeedback,
        applyRecipeDocument: d.applyRecipeDocument,
        renderDebugInfo: d.renderDebugInfo,
        previewPathLabel: d.previewPathLabel,
        rawBackendAbSummary: d.rawBackendAbSummary,
        rawBackendMode: d.rawBackendMode,
        setRawBackendMode: d.setRawBackendMode,
        rawLinearStageMode: d.rawLinearStageMode,
        setRawLinearStageMode: d.setRawLinearStageMode,
        rawLinearStageModeLabel: d.rawLinearStageModeLabel,
        rawQualityQaSummary: d.rawQualityQaSummary,
      },
    },
  };
}
