export function buildFilmLabGlobalKeydownProps({
  activePanel,
  studioWorkspace,
  hasImage,
  isStraightenToolArmed,
  isPreviewFullMode,
  showRenderDebugPanel,
  zoomRef,
  acceptCropDraft,
  acceptManualStraighten,
  cancelManualStraighten,
  setAdjustments,
  setIsPreviewFullMode,
  setIsShortcutHelpOpen,
  togglePreviewFullMode,
  fitClassic,
  jumpToOneToOne,
  setIsMetadataPanelOpen,
  cycleMetadataViewMode,
  cycleRawLinearStageMode,
  cycleCropOverlayMode,
  applyAutoExposure,
  applyAutoColor,
  stepZoom,
  nudgePan,
  triggerDustZip,
  triggerRawLeakZip,
  handleToolbarUndo,
  handleToolbarRedo,
  undoStackRef,
  redoStackRef,
}) {
  return {
    activePanel,
    studioWorkspace,
    hasImage,
    isStraightenToolArmed,
    isPreviewFullMode,
    showRenderDebugPanel,
    zoomRef,
    acceptCropDraft,
    acceptManualStraighten,
    cancelManualStraighten,
    setAdjustments,
    setIsPreviewFullMode,
    setIsShortcutHelpOpen,
    togglePreviewFullMode,
    fitClassic,
    jumpToOneToOne,
    setIsMetadataPanelOpen,
    cycleMetadataViewMode,
    cycleRawLinearStageMode,
    cycleCropOverlayMode,
    applyAutoExposure,
    applyAutoColor,
    stepZoom,
    nudgePan,
    triggerDustZip,
    triggerRawLeakZip,
    handleToolbarUndo,
    handleToolbarRedo,
    undoStackRef,
    redoStackRef,
  };
}

export function buildFilmLabToolbarProps({
  toolbarRef,
  sessionRestoreNotice,
  setSessionRestoreNotice,
  fileInputRef,
  hasImage,
  adjustments,
  toggleCompare,
  toggleFlip,
  rotateImage,
  stepZoom,
  displayedZoomPercent,
  isZoomBeyondFit,
  fitClassic,
  jumpToOneToOne,
  isShortcutHelpOpen,
  setIsShortcutHelpOpen,
  isPreviewFullMode,
  togglePreviewFullMode,
  toggleClipping,
  isMetadataPanelOpen,
  setIsMetadataPanelOpen,
  showRuntimeStatus,
  setShowRuntimeStatus,
  applyAutoExposure,
  applyAutoColor,
  handleToolbarReset,
  handleToolbarUndo,
  handleToolbarRedo,
  redoStackRef,
  copyToClipboard,
  pasteFromClipboard,
  clipboardFeedback,
  updateAdjustment,
  exportCubeLut,
  exportDebugReport,
  hasActiveSource,
  debugExportFeedback,
  batchState,
  isRawBackendForced,
  rawBackendModeLabel,
  batchFileInputRef,
  setPendingBatchFiles,
  setIsExportModalOpen,
  cancelBatch,
}) {
  return {
    toolbarRef,
    sessionRestoreNotice,
    onDismissSessionNotice: () => setSessionRestoreNotice(null),
    fileInputRef,
    hasImage,
    adjustments,
    toggleCompare,
    toggleFlip,
    rotateImage,
    stepZoom,
    displayedZoomPercent,
    isZoomBeyondFit,
    fitClassic,
    jumpToOneToOne,
    isShortcutHelpOpen,
    onToggleShortcutHelp: () => setIsShortcutHelpOpen((c) => !c),
    isPreviewFullMode,
    togglePreviewFullMode,
    toggleClipping,
    isMetadataPanelOpen,
    onToggleMetadataPanel: () => setIsMetadataPanelOpen((c) => !c),
    showRuntimeStatus,
    onToggleRuntimeStatus: () => setShowRuntimeStatus((c) => !c),
    applyAutoExposure,
    applyAutoColor,
    onToolbarReset: handleToolbarReset,
    onToolbarUndo: handleToolbarUndo,
    onToolbarRedo: handleToolbarRedo,
    redoDisabled: !redoStackRef.current.length,
    copyToClipboard,
    pasteFromClipboard,
    clipboardFeedback,
    updateAdjustment,
    exportCubeLut,
    exportDebugReport,
    hasActiveSource,
    debugExportFeedback,
    batchState,
    isRawBackendForced,
    rawBackendModeLabel,
    batchFileInputRef,
    onBatchFilesPicked: (files) => {
      setPendingBatchFiles(files);
      setIsExportModalOpen(true);
    },
    onOpenExportModal: () => setIsExportModalOpen(true),
    cancelBatch,
  };
}

export function buildFilmLabCanvasAreaProps({
  studioWorkspace,
  canvasAreaRef,
  hasImage,
  histogramCanvasRef,
  canvasCenterRef,
  canvasStageRef,
  handleCanvasWheel,
  rememberZoomAnchor,
  clearZoomAnchor,
  hasActiveSource,
  fileInputRef,
  pipelineInfo,
  canvasWrapperRef,
  isZoomBeyondFit,
  isPanning,
  canvasViewportSize,
  adjustments,
  setAdjustments,
  saveUndo,
  handleCanvasPointerDown,
  handleCanvasPointerMove,
  handleCanvasPointerUp,
  stopPanDragging,
  handleCanvasDoubleClick,
  showBlockingProcessing,
  showInlineProcessing,
  canvasRef,
  canvasPresentationStyle,
  isPixelPeepZoom,
  cropOverlay,
  compareMode,
  renderDebug,
  clearRenderPipelineAlert,
  renderPipelineAlert,
  showRuntimeStatus,
  runtimeStatusBadge,
  qualityStatus,
  fallbackExplanation,
  isMetadataPanelOpen,
  metadataViewMode,
  metadataViewModeLabels,
  cycleMetadataViewMode,
  copyMetadataToClipboard,
  metadataFeedback,
  displayedMetadataItems,
  handleFileUpload,
}) {
  return {
    studioWorkspace,
    canvasAreaRef,
    hasImage,
    histogramCanvasRef,
    canvasCenterRef,
    canvasStageRef,
    handleCanvasWheel,
    rememberZoomAnchor,
    clearZoomAnchor,
    hasActiveSource,
    fileInputRef,
    pipelineInfo,
    canvasWrapperRef,
    isZoomBeyondFit,
    isPanning,
    canvasViewportSize,
    adjustments,
    setAdjustments,
    saveUndo,
    handleCanvasPointerDown,
    handleCanvasPointerMove,
    handleCanvasPointerUp,
    stopPanDragging,
    handleCanvasDoubleClick,
    showBlockingProcessing,
    showInlineProcessing,
    canvasRef,
    canvasPresentationStyle,
    isPixelPeepZoom,
    cropOverlay,
    compareMode,
    renderDebug,
    clearRenderPipelineAlert,
    renderPipelineAlert,
    showRuntimeStatus,
    runtimeStatusBadge,
    qualityStatus,
    fallbackExplanation,
    isMetadataPanelOpen,
    metadataViewMode,
    metadataViewModeLabels,
    cycleMetadataViewMode,
    copyMetadataToClipboard,
    metadataFeedback,
    displayedMetadataItems,
    handleFileUpload,
  };
}

export function buildFilmLabRightPanelProps({
  maskWorkbench,
  rightSidebarRef,
  panelTabs,
  activePanel,
  onPanelTabChange,
  undoAction,
  redoAction,
  undoStackRef,
  redoStackRef,
  fullHistoryTimeline,
  renderSlider,
  renderCustomSlider,
  sliderDefs,
  adjustments,
  isInputProfile,
  resetAdjustments,
  resetSingleAdjustment,
  updateAdjustment,
  activeCurveCh,
  setActiveCurveCh,
  curvesCanvasRef,
  handleCurvePointerDown,
  handleCurveDoubleClick,
  resetCurves,
  mixerGroups,
  mixerColors,
  activeMixerGroup,
  setActiveMixerGroup,
  colorMixer,
  updateMixerValue,
  resetMixerValue,
  resetColorMixer,
  gradeZones,
  activeGradeZone,
  setActiveGradeZone,
  colorGrading,
  updateColorGradeValue,
  resetColorGradeValue,
  resetColorGrading,
  saveUndo,
  setIsAdjusting,
  setInteractionKind,
  handleSliderEnd,
  colorCalibration,
  updateCalibrationValue,
  resetCalibrationValue,
  resetColorCalibration,
  setLeak,
  setFrame,
  triggerDustZip,
  disableDustZip,
  triggerRawLeakZip,
  disableRawLeakZip,
  cropAspectPresets,
  activeCropAspectPreset,
  setCropAspectPreset,
  activeCropAspect,
  cropOverlayModes,
  activeCropOverlayMode,
  setCropOverlayMode,
  cycleCropOverlayMode,
  rotateCropOverlay,
  cancelManualStraighten,
  cancelCropDraft,
  rotateImage,
  toggleFlip,
  isStraightenToolArmed,
  setIsStraightenToolArmed,
  beginManualStraightenSession,
  runAutoStraighten,
  activeCropRectNorm,
  hasImage,
  activeFilm,
}) {
  return {
    maskWorkbench,
    rightSidebarRef,
    panelTabs,
    activePanel,
    onPanelTabChange,
    undoAction,
    redoAction,
    undoStackRef,
    redoStackRef,
    fullHistoryTimeline,
    renderSlider,
    renderCustomSlider,
    sliderDefs,
    adjustments,
    isInputProfile,
    resetAdjustments,
    resetSingleAdjustment,
    updateAdjustment,
    activeCurveCh,
    setActiveCurveCh,
    curvesCanvasRef,
    handleCurvePointerDown,
    handleCurveDoubleClick,
    resetCurves,
    mixerGroups,
    mixerColors,
    activeMixerGroup,
    setActiveMixerGroup,
    colorMixer,
    updateMixerValue,
    resetMixerValue,
    resetColorMixer,
    gradeZones,
    activeGradeZone,
    setActiveGradeZone,
    colorGrading,
    updateColorGradeValue,
    resetColorGradeValue,
    resetColorGrading,
    saveUndo,
    setIsAdjusting,
    setInteractionKind,
    handleSliderEnd,
    colorCalibration,
    updateCalibrationValue,
    resetCalibrationValue,
    resetColorCalibration,
    setLeak,
    setFrame,
    triggerDustZip,
    disableDustZip,
    triggerRawLeakZip,
    disableRawLeakZip,
    cropAspectPresets,
    activeCropAspectPreset,
    setCropAspectPreset,
    activeCropAspect,
    cropOverlayModes,
    activeCropOverlayMode,
    setCropOverlayMode,
    cycleCropOverlayMode,
    rotateCropOverlay,
    cancelManualStraighten,
    cancelCropDraft,
    rotateImage,
    toggleFlip,
    isStraightenToolArmed,
    setIsStraightenToolArmed,
    beginManualStraightenSession,
    runAutoStraighten,
    activeCropRectNorm,
    hasImage,
    activeFilm,
  };
}
export function buildFilmLabProfilesSidebarProps({
  sidebarRef,
  categoryTabs,
  visibleFilms,
  activeFilmIndex,
  activeCategory,
  searchQuery,
  setActiveCategory,
  setSearchQuery,
  selectFilm,
}) {
  return {
    sidebarRef,
    categoryTabs,
    visibleFilms,
    activeFilmIndex,
    activeCategory,
    searchQuery,
    onActiveCategoryChange: setActiveCategory,
    onSearchQueryChange: setSearchQuery,
    onSelectFilm: selectFilm,
  };
}

export function buildFilmLabShortcutHelpProps({ isShortcutHelpOpen, setIsShortcutHelpOpen }) {
  return {
    open: isShortcutHelpOpen,
    onClose: () => setIsShortcutHelpOpen(false),
  };
}

export function buildFilmLabSessionRestorePromptProps({
  sessionRestorePrompt,
  confirmSessionRestore,
  declineSessionRestore,
}) {
  return {
    open: Boolean(sessionRestorePrompt),
    savedAt: sessionRestorePrompt?.savedAt ?? 0,
    fileName: sessionRestorePrompt?.fileName ?? '',
    onConfirm: confirmSessionRestore,
    onDecline: declineSessionRestore,
  };
}

export function buildFilmLabExportModalProps({
  isExportModalOpen,
  pendingBatchFiles,
  setIsExportModalOpen,
  setPendingBatchFiles,
  processBatch,
  exportImage,
}) {
  return {
    open: isExportModalOpen,
    pendingBatchFiles,
    onClose: () => {
      setIsExportModalOpen(false);
      setPendingBatchFiles(null);
    },
    processBatch,
    exportImage,
  };
}
