import { useMemo } from 'react';
import { CROP_HANDLE_DEFS } from './crop/cropConstants.js';

export function useFilmLabShellOverlayProps({
  shouldRenderCropOverlay,
  canvasPresentationStyle,
  cropMaskPath,
  cropRectPercent,
  activeCropOverlayMode,
  activeCropOverlayOrientation,
  cropGuideTransform,
  cropOverlayGuideElements,
  isStraightenToolArmed,
  handleStraightenPointerDown,
  straightenGuidePercent,
  cropOverlayInteractionRef,
  acceptManualStraighten,
  handleCropOverlayDoubleClick,
  handleStraightenPointerMove,
  handleStraightenPointerUp,
  handleStraightenPointerCancel,
  handleCropPointerMove,
  handleCropPointerUp,
  handleCropPointerCancel,
  cropMoveZoneRect,
  cropHandles,
  cropHandleHitboxes,
  handleCropHandlePointerDown,
  hasPendingCropChanges,
  acceptCropDraft,
  isOverlayInteractionEnabled,
  showRenderDebugPanel,
  exportDebugReport,
  debugExportFeedback,
  renderDebugInfo,
  previewPathLabel,
  rawBackendAbSummary,
  rawBackendMode,
  setRawBackendMode,
  rawLinearStageMode,
  setRawLinearStageMode,
  rawLinearStageModeLabel,
  rawQualityQaSummary,
}) {
  const cropOverlay = useMemo(
    () => ({
      open: shouldRenderCropOverlay,
      canvasPresentationStyle,
      cropMaskPath,
      cropRectPercent,
      activeCropOverlayMode,
      activeCropOverlayOrientation,
      cropGuideTransform,
      cropOverlayGuideElements,
      isStraightenToolArmed,
      handleStraightenPointerDown,
      straightenGuidePercent,
      cropOverlayInteractionRef,
      acceptManualStraighten,
      handleCropOverlayDoubleClick,
      handleStraightenPointerMove,
      handleStraightenPointerUp,
      handleStraightenPointerCancel,
      handleCropPointerMove,
      handleCropPointerUp,
      handleCropPointerCancel,
      cropMoveZoneRect,
      cropHandles,
      cropHandleHitboxes,
      cropHandleDefs: CROP_HANDLE_DEFS,
      handleCropHandlePointerDown,
      hasPendingCropChanges,
      acceptCropDraft,
      isOverlayInteractionEnabled,
    }),
    [
      shouldRenderCropOverlay,
      canvasPresentationStyle,
      cropMaskPath,
      cropRectPercent,
      activeCropOverlayMode,
      activeCropOverlayOrientation,
      cropGuideTransform,
      cropOverlayGuideElements,
      isStraightenToolArmed,
      handleStraightenPointerDown,
      straightenGuidePercent,
      acceptManualStraighten,
      handleCropOverlayDoubleClick,
      handleStraightenPointerMove,
      handleStraightenPointerUp,
      handleStraightenPointerCancel,
      handleCropPointerMove,
      handleCropPointerUp,
      handleCropPointerCancel,
      cropMoveZoneRect,
      cropHandles,
      cropHandleHitboxes,
      handleCropHandlePointerDown,
      hasPendingCropChanges,
      acceptCropDraft,
      isOverlayInteractionEnabled,
    ]
  );

  const renderDebug = useMemo(
    () => ({
      open: showRenderDebugPanel,
      exportDebugReport,
      debugExportFeedback,
      renderDebugInfo,
      previewPathLabel,
      rawBackendAbSummary,
      rawBackendMode,
      setRawBackendMode,
      rawLinearStageMode,
      setRawLinearStageMode,
      rawLinearStageModeLabel,
      rawQualityQaSummary,
    }),
    [
      showRenderDebugPanel,
      exportDebugReport,
      debugExportFeedback,
      renderDebugInfo,
      previewPathLabel,
      rawBackendAbSummary,
      rawBackendMode,
      setRawBackendMode,
      rawLinearStageMode,
      setRawLinearStageMode,
      rawLinearStageModeLabel,
      rawQualityQaSummary,
    ]
  );

  return { cropOverlay, renderDebug };
}
