export const METADATA_VIEW_MODES = ['compact', 'exif', 'full'];
export const METADATA_VIEW_MODE_LABEL = {
  compact: 'Kompakt',
  exif: 'EXIF',
  full: 'Pełny',
};

export const RAW_BACKEND_MODES = ['auto', 'quicklook', 'sips'];
export const RAW_BACKEND_MODE_LABELS = Object.freeze({
  auto: 'AUTO',
  quicklook: 'QL',
  sips: 'SIPS',
});
export const RAW_LINEAR_STAGE_MODES = ['auto', 'on', 'off'];
export const RAW_LINEAR_STAGE_MODE_LABELS = Object.freeze({
  auto: 'AUTO',
  on: 'ON',
  off: 'OFF',
});
export const RAW_QA_THRESHOLDS = Object.freeze({
  highlightWarn: 0.018,
  highlightFail: 0.05,
  shadowWarn: 0.024,
  shadowFail: 0.06,
  abMeanDeltaWarn: 9,
  abMeanDeltaFail: 20,
});

export const SLIDER_DEFS = {
  strength: { label: 'Siła profilu', min: 0, max: 100 },
  exposure: { label: 'Ekspozycja', min: -100, max: 100 },
  contrast: { label: 'Kontrast', min: -100, max: 100 },
  highlights: { label: 'Światła', min: -100, max: 100 },
  shadows: { label: 'Cienie', min: -100, max: 100 },
  whites: { label: 'Biele', min: -100, max: 100 },
  blacks: { label: 'Czarne', min: -100, max: 100 },
  level: { label: 'Poziom', min: -20, max: 20 },
  cropZoom: { label: 'Powiększenie kadru', min: 100, max: 200 },
  cropX: { label: 'Przesunięcie poziome', min: -100, max: 100 },
  cropY: { label: 'Przesunięcie pionowe', min: -100, max: 100 },
  fade: { label: 'Fade', min: 0, max: 100 },
  clarity: { label: 'Clarity', min: -100, max: 100 },
  dehaze: { label: 'Dehaze', min: -100, max: 100 },
  temp: { label: 'Temperatura', min: -100, max: 100 },
  tint: { label: 'Tint', min: -100, max: 100 },
  saturation: { label: 'Nasycenie', min: -100, max: 100 },
  vibrance: { label: 'Vibrance', min: -100, max: 100 },
  curveLumaMix: { label: 'Luma krzywej RGB', min: 0, max: 100 },
  userGrain: { label: 'Ilość', min: 0, max: 100 },
  userGrainSize: { label: 'Rozmiar', min: 10, max: 100 },
  chromAb: { label: 'Aberracja Chromatyczna', min: 0, max: 100 },
  bloom: { label: 'Bloom / Glow', min: 0, max: 100 },
  dust: { label: 'Dust & Scratches', min: 0, max: 100 },
  userVignette: { label: 'Siła', min: 0, max: 100 },
  halation: { label: 'Siła halacji', min: 0, max: 100 },
  halRadius: { label: 'Promień', min: 5, max: 80 },
  halThresh: { label: 'Próg jasności', min: 120, max: 250 },
  halHue: { label: 'Odcień (R↔B)', min: -100, max: 100 },
  anamorph: { label: 'Siła smug', min: 0, max: 100 },
  streakLen: { label: 'Długość smug', min: 10, max: 100 },
  gateWeave: { label: 'Gate weave', min: 0, max: 100 },
  doubleExposureAmount: { label: 'Double exposure', min: 0, max: 100 },
  brushMaskRadius: { label: 'Promień pędzla', min: 8, max: 240 },
  brushMaskFeather: { label: 'Miękkość pędzla', min: 0, max: 100 },
  brushMaskFlow: { label: 'Przepływ', min: 1, max: 100 },
  brushMaskDensity: { label: 'Gęstość', min: 1, max: 100 },
  brushMaskEdgeSensitivity: { label: 'Pędzel: krawędź', min: 0, max: 100 },
  brushMaskExposure: { label: 'Naświetlenie (maska)', min: -100, max: 100 },
  brushMaskContrast: { label: 'Gradacja (kontrast)', min: -100, max: 100 },
  brushMaskHighlights: { label: 'Światła', min: -100, max: 100 },
  brushMaskShadows: { label: 'Cienie', min: -100, max: 100 },
  brushMaskWhites: { label: 'Jasne partie (biele)', min: -100, max: 100 },
  brushMaskBlacks: { label: 'Głębokie cienie', min: -100, max: 100 },
  brushMaskTemp: { label: 'Ocieplenie / oziębienie', min: -100, max: 100 },
  brushMaskTint: { label: 'Dominanta barwna (tint)', min: -100, max: 100 },
  brushMaskSaturation: { label: 'Nasycenie (maska)', min: -100, max: 100 },
  linearMaskAngle: { label: 'Kąt gradientu', min: -180, max: 180 },
  linearMaskFeather: { label: 'Miękkość gradientu', min: 0, max: 100 },
  linearMaskOffset: { label: 'Przesunięcie gradientu', min: -100, max: 100 },
  radialMaskCenterX: { label: 'Środek X', min: 0, max: 100 },
  radialMaskCenterY: { label: 'Środek Y', min: 0, max: 100 },
  radialMaskRadius: { label: 'Promień radial', min: 5, max: 100 },
  radialMaskFeather: { label: 'Miękkość radial', min: 0, max: 100 },
  lumaMaskMin: { label: 'Luma min', min: 0, max: 100 },
  lumaMaskMax: { label: 'Luma max', min: 0, max: 100 },
  lumaMaskFeather: { label: 'Miękkość luma', min: 0, max: 100 },
  depthMaskMin: { label: 'Depth range — min', min: 0, max: 100 },
  depthMaskMax: { label: 'Depth range — max', min: 0, max: 100 },
  depthMaskFeather: { label: 'Depth range — feather', min: 0, max: 100 },
  colorMaskHueCenter: { label: 'Hue center', min: 0, max: 360 },
  colorMaskHueWidth: { label: 'Hue width', min: 5, max: 180 },
  colorMaskFeather: { label: 'Miękkość hue', min: 0, max: 100 },
  colorMaskChromaMin: { label: 'Chroma min', min: 0, max: 100 },
  colorMaskChromaMax: { label: 'Chroma max', min: 0, max: 100 },
  localMaskOpacity: { label: 'Krycie maski', min: 0, max: 100 },
  orangeMaskCorrection: { label: 'Maska pomarańczowa (C-41)', min: 0, max: 100 },
  pushPullEv: { label: 'Push / Pull (EV)', min: -3, max: 3 },
  emulsionReciprocityComp: { label: 'Reciprocity (długie czasy)', min: 0, max: 100 },
  emulsionEdgeAcutance: { label: 'Ostrość krawędzi (MTF)', min: 0, max: 100 },
};

export const SLIDER_DRAG_ACTIVATION_THRESHOLD_PX = 4;
export const SLIDER_RELEASE_FAILSAFE_MS = 260;
