return {
  ["bw"] = {
    stages = {
      ['01'] = {
        { title = "Delta 100", path = "profiles/modular/color_systems/bw/6.ML_Delta100.xmp" },
        { title = "Foma 100", path = "profiles/modular/color_systems/bw/[01] Foma 100.xmp" },
        { title = "Foma 400", path = "profiles/modular/color_systems/bw/[01] Foma 400.xmp" },
        { title = "Fomapan 100", path = "profiles/modular/color_systems/bw/5.ML_Fomapan100.xmp" },
        { title = "Fomapan 400", path = "profiles/modular/color_systems/bw/4.ML_Fomapan400.xmp" },
        { title = "HP5", path = "profiles/modular/color_systems/bw/[01] HP5.xmp" },
        { title = "HP5 400", path = "profiles/modular/color_systems/bw/1.ML_HP5_400.xmp" },
        { title = "T-Max 400", path = "profiles/modular/color_systems/bw/3.ML_TMAX_400.xmp" },
        { title = "Tri-X 400", path = "profiles/modular/color_systems/bw/2.ML_TRIX_400.xmp" },
        { title = "TRI-X BASE", path = "profiles/modular/color_systems/bw/01_TRI-X_BASE.xmp" },
        { title = "Vision BW", path = "profiles/modular/color_systems/bw/[01] Vision BW.xmp" },
        { title = "XP2", path = "profiles/modular/color_systems/bw/[01] XP2.xmp" },
        { title = "XP2 Super", path = "profiles/modular/color_systems/bw/8.ML_XP2_SUPER.xmp" },
      },
      ['02'] = {
        { title = "Natural", path = "profiles/modular/color_systems/bw/[02] Natural.xmp" },
        { title = "Soft Control", path = "profiles/modular/color_systems/bw/[02] Soft Control.xmp" },
      },
      ['03'] = {
        { title = "Contrast", path = "profiles/modular/color_systems/bw/[03] Contrast.xmp" },
        { title = "Crisp", path = "profiles/modular/color_systems/bw/[03] Crisp.xmp" },
        { title = "Depth", path = "profiles/modular/color_systems/bw/[03] Depth.xmp" },
        { title = "Film Fade", path = "profiles/modular/color_systems/bw/[03] Film Fade.xmp" },
        { title = "Soft", path = "profiles/modular/color_systems/bw/[03] Soft.xmp" },
        { title = "Subject Focus", path = "profiles/modular/color_systems/bw/[03] Subject Focus.xmp" },
        { title = "Subject Lift", path = "profiles/modular/color_systems/bw/[03] Subject Lift.xmp" },
        { title = "Tonal Separation", path = "profiles/modular/color_systems/bw/[03] Tonal Separation.xmp" },
      },
      ['04'] = {
        { title = "Deep Shadows", path = "profiles/modular/color_systems/bw/[04] Deep Shadows.xmp" },
        { title = "Matte Fade", path = "profiles/modular/color_systems/bw/[04] Matte Fade.xmp" },
        { title = "Soft Highlights", path = "profiles/modular/color_systems/bw/[04] Soft Highlights.xmp" },
        { title = "Texture", path = "profiles/modular/color_systems/bw/[04] Texture.xmp" },
      },
    },
  },
  ["ektar"] = {
    stages = {
      ['01'] = {
        { title = "Ektar 100", path = "profiles/modular/color_systems/ektar/[01] Ektar 100.xmp" },
      },
      ['02'] = {
        { title = "Clean Canvas", path = "profiles/modular/color_systems/ektar/[02] Clean Canvas.xmp" },
        { title = "Natural", path = "profiles/modular/color_systems/ektar/[02] Natural.xmp" },
        { title = "Reduce Redness", path = "profiles/modular/color_systems/ektar/[02] Reduce Redness.xmp" },
        { title = "Soft Touch", path = "profiles/modular/color_systems/ektar/[02] Soft Touch.xmp" },
        { title = "Warm Control", path = "profiles/modular/color_systems/ektar/[02] Warm Control.xmp" },
        { title = "Warm Fix", path = "profiles/modular/color_systems/ektar/[02] Warm Fix.xmp" },
      },
      ['03'] = {
        { title = "Calm Colors", path = "profiles/modular/color_systems/ektar/[03] Calm Colors.xmp" },
        { title = "Color Separation", path = "profiles/modular/color_systems/ektar/[03] Color Separation.xmp" },
        { title = "Contrast", path = "profiles/modular/color_systems/ektar/[03] Contrast.xmp" },
        { title = "Depth", path = "profiles/modular/color_systems/ektar/[03] Depth.xmp" },
        { title = "Light Wrap", path = "profiles/modular/color_systems/ektar/[03] Light Wrap.xmp" },
        { title = "Subject Focus", path = "profiles/modular/color_systems/ektar/[03] Subject Focus.xmp" },
        { title = "Subject Polish", path = "profiles/modular/color_systems/ektar/[03] Subject Polish.xmp" },
      },
      ['04'] = {
        { title = "Deep Shadows", path = "profiles/modular/color_systems/ektar/[04] Deep Shadows.xmp" },
        { title = "Soft Highlights", path = "profiles/modular/color_systems/ektar/[04] Soft Highlights.xmp" },
        { title = "Soft Pastel", path = "profiles/modular/color_systems/ektar/[04] Soft Pastel.xmp" },
        { title = "Texture", path = "profiles/modular/color_systems/ektar/[04] Texture.xmp" },
      },
    },
  },
  ["ektar_color_system_patched.zip"] = {
    stages = {
      ['01'] = {
        { title = "Ektar 100", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[01] Ektar 100.xmp" },
      },
      ['02'] = {
        { title = "Clean Canvas", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[02] Clean Canvas.xmp" },
        { title = "Natural", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[02] Natural.xmp" },
        { title = "Reduce Redness", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[02] Reduce Redness.xmp" },
        { title = "Soft Touch", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[02] Soft Touch.xmp" },
        { title = "Warm Control", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[02] Warm Control.xmp" },
        { title = "Warm Fix", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[02] Warm Fix.xmp" },
      },
      ['03'] = {
        { title = "Calm Colors", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[03] Calm Colors.xmp" },
        { title = "Color Separation", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[03] Color Separation.xmp" },
        { title = "Contrast", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[03] Contrast.xmp" },
        { title = "Depth", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[03] Depth.xmp" },
        { title = "Light Wrap", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[03] Light Wrap.xmp" },
        { title = "Subject Focus", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[03] Subject Focus.xmp" },
        { title = "Subject Polish", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[03] Subject Polish.xmp" },
      },
      ['04'] = {
        { title = "Deep Shadows", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[04] Deep Shadows.xmp" },
        { title = "Soft Highlights", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[04] Soft Highlights.xmp" },
        { title = "Soft Pastel", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[04] Soft Pastel.xmp" },
        { title = "Texture", path = "profiles/modular/color_systems/ektar_color_system_patched.zip/[04] Texture.xmp" },
      },
    },
  },
  ["fuji"] = {
    stages = {
      ['01'] = {
        { title = "Astia 100F", path = "profiles/modular/color_systems/fuji/[01] Astia 100F.xmp" },
        { title = "Fuji 400H", path = "profiles/modular/color_systems/fuji/[01] Fuji 400H.xmp" },
        { title = "Natura 1600", path = "profiles/modular/color_systems/fuji/[01] Natura 1600.xmp" },
        { title = "Provia 100F", path = "profiles/modular/color_systems/fuji/[01] Provia 100F.xmp" },
        { title = "Superia 1600", path = "profiles/modular/color_systems/fuji/[01] Superia 1600.xmp" },
        { title = "Superia 400", path = "profiles/modular/color_systems/fuji/[01] Superia 400.xmp" },
        { title = "Velvia 50", path = "profiles/modular/color_systems/fuji/[01] Velvia 50.xmp" },
      },
      ['02'] = {
        { title = "Clean Canvas", path = "profiles/modular/color_systems/fuji/[02] Clean Canvas.xmp" },
        { title = "Cool Balance", path = "profiles/modular/color_systems/fuji/[02] Cool Balance.xmp" },
        { title = "Indoor Balance", path = "profiles/modular/color_systems/fuji/[02] Indoor Balance.xmp" },
        { title = "Natural", path = "profiles/modular/color_systems/fuji/[02] Natural.xmp" },
        { title = "Reduce Redness", path = "profiles/modular/color_systems/fuji/[02] Reduce Redness.xmp" },
        { title = "Shadow Open", path = "profiles/modular/color_systems/fuji/[02] Shadow Open.xmp" },
        { title = "Soft Control", path = "profiles/modular/color_systems/fuji/[02] Soft Control.xmp" },
        { title = "Soft Touch", path = "profiles/modular/color_systems/fuji/[02] Soft Touch.xmp" },
        { title = "Warm Control", path = "profiles/modular/color_systems/fuji/[02] Warm Control.xmp" },
        { title = "Warm Fix", path = "profiles/modular/color_systems/fuji/[02] Warm Fix.xmp" },
      },
      ['03'] = {
        { title = "Calm Colors", path = "profiles/modular/color_systems/fuji/[03] Calm Colors.xmp" },
        { title = "Color Separation", path = "profiles/modular/color_systems/fuji/[03] Color Separation.xmp" },
        { title = "Contrast", path = "profiles/modular/color_systems/fuji/[03] Contrast.xmp" },
        { title = "Crisp", path = "profiles/modular/color_systems/fuji/[03] Crisp.xmp" },
        { title = "Depth", path = "profiles/modular/color_systems/fuji/[03] Depth.xmp" },
        { title = "Film Fade", path = "profiles/modular/color_systems/fuji/[03] Film Fade.xmp" },
        { title = "Light Wrap", path = "profiles/modular/color_systems/fuji/[03] Light Wrap.xmp" },
        { title = "Pastel", path = "profiles/modular/color_systems/fuji/[03] Pastel.xmp" },
        { title = "Soft", path = "profiles/modular/color_systems/fuji/[03] Soft.xmp" },
        { title = "Subject Focus", path = "profiles/modular/color_systems/fuji/[03] Subject Focus.xmp" },
        { title = "Subject Polish", path = "profiles/modular/color_systems/fuji/[03] Subject Polish.xmp" },
      },
      ['04'] = {
        { title = "Deep Shadows", path = "profiles/modular/color_systems/fuji/[04] Deep Shadows.xmp" },
        { title = "Soft Highlights", path = "profiles/modular/color_systems/fuji/[04] Soft Highlights.xmp" },
        { title = "Soft Pastel", path = "profiles/modular/color_systems/fuji/[04] Soft Pastel.xmp" },
        { title = "Texture", path = "profiles/modular/color_systems/fuji/[04] Texture.xmp" },
      },
    },
  },
  ["fuji_consumer"] = {
    stages = {
      ['01'] = {
        { title = "Natura 1600", path = "profiles/modular/color_systems/fuji_consumer/6.ML_Natura1600.xmp" },
        { title = "Superia 1600", path = "profiles/modular/color_systems/fuji_consumer/5.ML_Superia1600.xmp" },
        { title = "Superia X-Tra 400", path = "profiles/modular/color_systems/fuji_consumer/4.ML_SuperiaXTRA400.xmp" },
      },
      ['02'] = {
        { title = "Clean Canvas", path = "profiles/modular/color_systems/fuji/[02] Clean Canvas.xmp" },
        { title = "Cool Balance", path = "profiles/modular/color_systems/fuji/[02] Cool Balance.xmp" },
        { title = "Indoor Balance", path = "profiles/modular/color_systems/fuji/[02] Indoor Balance.xmp" },
        { title = "Natural", path = "profiles/modular/color_systems/fuji/[02] Natural.xmp" },
        { title = "Reduce Redness", path = "profiles/modular/color_systems/fuji/[02] Reduce Redness.xmp" },
        { title = "Shadow Open", path = "profiles/modular/color_systems/fuji/[02] Shadow Open.xmp" },
        { title = "Soft Control", path = "profiles/modular/color_systems/fuji/[02] Soft Control.xmp" },
        { title = "Soft Touch", path = "profiles/modular/color_systems/fuji/[02] Soft Touch.xmp" },
        { title = "Warm Control", path = "profiles/modular/color_systems/fuji/[02] Warm Control.xmp" },
        { title = "Warm Fix", path = "profiles/modular/color_systems/fuji/[02] Warm Fix.xmp" },
      },
      ['03'] = {
        { title = "Calm Colors", path = "profiles/modular/color_systems/fuji/[03] Calm Colors.xmp" },
        { title = "Color Separation", path = "profiles/modular/color_systems/fuji/[03] Color Separation.xmp" },
        { title = "Contrast", path = "profiles/modular/color_systems/fuji/[03] Contrast.xmp" },
        { title = "Crisp", path = "profiles/modular/color_systems/fuji/[03] Crisp.xmp" },
        { title = "Depth", path = "profiles/modular/color_systems/fuji/[03] Depth.xmp" },
        { title = "Film Fade", path = "profiles/modular/color_systems/fuji/[03] Film Fade.xmp" },
        { title = "Light Wrap", path = "profiles/modular/color_systems/fuji/[03] Light Wrap.xmp" },
        { title = "Pastel", path = "profiles/modular/color_systems/fuji/[03] Pastel.xmp" },
        { title = "Soft", path = "profiles/modular/color_systems/fuji/[03] Soft.xmp" },
        { title = "Subject Focus", path = "profiles/modular/color_systems/fuji/[03] Subject Focus.xmp" },
        { title = "Subject Polish", path = "profiles/modular/color_systems/fuji/[03] Subject Polish.xmp" },
      },
      ['04'] = {
        { title = "Deep Shadows", path = "profiles/modular/color_systems/fuji/[04] Deep Shadows.xmp" },
        { title = "Soft Highlights", path = "profiles/modular/color_systems/fuji/[04] Soft Highlights.xmp" },
        { title = "Soft Pastel", path = "profiles/modular/color_systems/fuji/[04] Soft Pastel.xmp" },
        { title = "Texture", path = "profiles/modular/color_systems/fuji/[04] Texture.xmp" },
      },
    },
  },
  ["fuji_pro"] = {
    stages = {
      ['01'] = {
        { title = "Fuji Pro 400H", path = "profiles/modular/color_systems/fuji_pro/1.ML_FujiPro400H.xmp" },
      },
      ['02'] = {
        { title = "Clean Canvas", path = "profiles/modular/color_systems/fuji/[02] Clean Canvas.xmp" },
        { title = "Cool Balance", path = "profiles/modular/color_systems/fuji/[02] Cool Balance.xmp" },
        { title = "Indoor Balance", path = "profiles/modular/color_systems/fuji/[02] Indoor Balance.xmp" },
        { title = "Natural", path = "profiles/modular/color_systems/fuji/[02] Natural.xmp" },
        { title = "Reduce Redness", path = "profiles/modular/color_systems/fuji/[02] Reduce Redness.xmp" },
        { title = "Shadow Open", path = "profiles/modular/color_systems/fuji/[02] Shadow Open.xmp" },
        { title = "Soft Control", path = "profiles/modular/color_systems/fuji/[02] Soft Control.xmp" },
        { title = "Soft Touch", path = "profiles/modular/color_systems/fuji/[02] Soft Touch.xmp" },
        { title = "Warm Control", path = "profiles/modular/color_systems/fuji/[02] Warm Control.xmp" },
        { title = "Warm Fix", path = "profiles/modular/color_systems/fuji/[02] Warm Fix.xmp" },
      },
      ['03'] = {
        { title = "Calm Colors", path = "profiles/modular/color_systems/fuji/[03] Calm Colors.xmp" },
        { title = "Color Separation", path = "profiles/modular/color_systems/fuji/[03] Color Separation.xmp" },
        { title = "Contrast", path = "profiles/modular/color_systems/fuji/[03] Contrast.xmp" },
        { title = "Crisp", path = "profiles/modular/color_systems/fuji/[03] Crisp.xmp" },
        { title = "Depth", path = "profiles/modular/color_systems/fuji/[03] Depth.xmp" },
        { title = "Film Fade", path = "profiles/modular/color_systems/fuji/[03] Film Fade.xmp" },
        { title = "Light Wrap", path = "profiles/modular/color_systems/fuji/[03] Light Wrap.xmp" },
        { title = "Pastel", path = "profiles/modular/color_systems/fuji/[03] Pastel.xmp" },
        { title = "Soft", path = "profiles/modular/color_systems/fuji/[03] Soft.xmp" },
        { title = "Subject Focus", path = "profiles/modular/color_systems/fuji/[03] Subject Focus.xmp" },
        { title = "Subject Polish", path = "profiles/modular/color_systems/fuji/[03] Subject Polish.xmp" },
      },
      ['04'] = {
        { title = "Deep Shadows", path = "profiles/modular/color_systems/fuji/[04] Deep Shadows.xmp" },
        { title = "Soft Highlights", path = "profiles/modular/color_systems/fuji/[04] Soft Highlights.xmp" },
        { title = "Soft Pastel", path = "profiles/modular/color_systems/fuji/[04] Soft Pastel.xmp" },
        { title = "Texture", path = "profiles/modular/color_systems/fuji/[04] Texture.xmp" },
      },
    },
  },
  ["fuji_slide"] = {
    stages = {
      ['01'] = {
        { title = "Astia 100F", path = "profiles/modular/color_systems/fuji_slide/7.ML_Astia100F.xmp" },
        { title = "Provia 100F", path = "profiles/modular/color_systems/fuji_slide/3.ML_Provia100F.xmp" },
        { title = "Velvia 50", path = "profiles/modular/color_systems/fuji_slide/2.ML_Velvia50.xmp" },
      },
      ['02'] = {
        { title = "Clean Canvas", path = "profiles/modular/color_systems/fuji/[02] Clean Canvas.xmp" },
        { title = "Cool Balance", path = "profiles/modular/color_systems/fuji/[02] Cool Balance.xmp" },
        { title = "Indoor Balance", path = "profiles/modular/color_systems/fuji/[02] Indoor Balance.xmp" },
        { title = "Natural", path = "profiles/modular/color_systems/fuji/[02] Natural.xmp" },
        { title = "Reduce Redness", path = "profiles/modular/color_systems/fuji/[02] Reduce Redness.xmp" },
        { title = "Shadow Open", path = "profiles/modular/color_systems/fuji/[02] Shadow Open.xmp" },
        { title = "Soft Control", path = "profiles/modular/color_systems/fuji/[02] Soft Control.xmp" },
        { title = "Soft Touch", path = "profiles/modular/color_systems/fuji/[02] Soft Touch.xmp" },
        { title = "Warm Control", path = "profiles/modular/color_systems/fuji/[02] Warm Control.xmp" },
        { title = "Warm Fix", path = "profiles/modular/color_systems/fuji/[02] Warm Fix.xmp" },
      },
      ['03'] = {
        { title = "Calm Colors", path = "profiles/modular/color_systems/fuji/[03] Calm Colors.xmp" },
        { title = "Color Separation", path = "profiles/modular/color_systems/fuji/[03] Color Separation.xmp" },
        { title = "Contrast", path = "profiles/modular/color_systems/fuji/[03] Contrast.xmp" },
        { title = "Crisp", path = "profiles/modular/color_systems/fuji/[03] Crisp.xmp" },
        { title = "Depth", path = "profiles/modular/color_systems/fuji/[03] Depth.xmp" },
        { title = "Film Fade", path = "profiles/modular/color_systems/fuji/[03] Film Fade.xmp" },
        { title = "Light Wrap", path = "profiles/modular/color_systems/fuji/[03] Light Wrap.xmp" },
        { title = "Pastel", path = "profiles/modular/color_systems/fuji/[03] Pastel.xmp" },
        { title = "Soft", path = "profiles/modular/color_systems/fuji/[03] Soft.xmp" },
        { title = "Subject Focus", path = "profiles/modular/color_systems/fuji/[03] Subject Focus.xmp" },
        { title = "Subject Polish", path = "profiles/modular/color_systems/fuji/[03] Subject Polish.xmp" },
      },
      ['04'] = {
        { title = "Deep Shadows", path = "profiles/modular/color_systems/fuji/[04] Deep Shadows.xmp" },
        { title = "Soft Highlights", path = "profiles/modular/color_systems/fuji/[04] Soft Highlights.xmp" },
        { title = "Soft Pastel", path = "profiles/modular/color_systems/fuji/[04] Soft Pastel.xmp" },
        { title = "Texture", path = "profiles/modular/color_systems/fuji/[04] Texture.xmp" },
      },
    },
  },
  ["gold"] = {
    stages = {
      ['01'] = {
        { title = "Kodak ColorPlus 200", path = "profiles/modular/color_systems/gold/8.ML_ColorPlus200.xmp" },
        { title = "Kodak Gold 200", path = "profiles/modular/color_systems/gold/1.ML_Gold200.xmp" },
      },
      ['02'] = {
        { title = "Clean Canvas", path = "profiles/modular/color_systems/portra/[02] Clean Canvas.xmp" },
        { title = "Highlight Soft", path = "profiles/modular/color_systems/portra/[02] Highlight Soft.xmp" },
        { title = "Indoor Balance", path = "profiles/modular/color_systems/portra/[02] Indoor Balance.xmp" },
        { title = "Natural", path = "profiles/modular/color_systems/portra/[02] Natural.xmp" },
        { title = "Reduce Redness", path = "profiles/modular/color_systems/portra/[02] Reduce Redness.xmp" },
        { title = "Shadow Open", path = "profiles/modular/color_systems/portra/[02] Shadow Open.xmp" },
        { title = "Soft Control", path = "profiles/modular/color_systems/portra/[02] Soft Control.xmp" },
        { title = "Soft Touch", path = "profiles/modular/color_systems/portra/[02] Soft Touch.xmp" },
        { title = "Warm Control", path = "profiles/modular/color_systems/portra/[02] Warm Control.xmp" },
        { title = "Warm Fix", path = "profiles/modular/color_systems/portra/[02] Warm Fix.xmp" },
      },
      ['03'] = {
        { title = "Calm Colors", path = "profiles/modular/color_systems/portra/[03] Calm Colors.xmp" },
        { title = "Color Separation", path = "profiles/modular/color_systems/portra/[03] Color Separation.xmp" },
        { title = "Depth", path = "profiles/modular/color_systems/portra/[03] Depth.xmp" },
        { title = "Film Fade", path = "profiles/modular/color_systems/portra/[03] Film Fade.xmp" },
        { title = "Light Wrap", path = "profiles/modular/color_systems/portra/[03] Light Wrap.xmp" },
        { title = "Soft", path = "profiles/modular/color_systems/portra/[03] Soft.xmp" },
        { title = "Subject Focus", path = "profiles/modular/color_systems/portra/[03] Subject Focus.xmp" },
        { title = "Subject Polish", path = "profiles/modular/color_systems/portra/[03] Subject Polish.xmp" },
      },
      ['04'] = {
        { title = "Deep Shadows", path = "profiles/modular/color_systems/portra/[04] Deep Shadows.xmp" },
        { title = "Soft Highlights", path = "profiles/modular/color_systems/portra/[04] Soft Highlights.xmp" },
        { title = "Soft Pastel", path = "profiles/modular/color_systems/portra/[04] Soft Pastel.xmp" },
        { title = "Texture", path = "profiles/modular/color_systems/portra/[04] Texture.xmp" },
      },
    },
  },
  ["kodachrome"] = {
    stages = {
      ['01'] = {
        { title = "Kodachrome 25", path = "profiles/modular/color_systems/kodachrome/6.ML_Kodachrome25.xmp" },
        { title = "Kodachrome 64", path = "profiles/modular/color_systems/kodachrome/7.ML_Kodachrome64.xmp" },
      },
      ['02'] = {
        { title = "Clean Canvas", path = "profiles/modular/color_systems/kodachrome/[02] Clean Canvas.xmp" },
        { title = "Natural", path = "profiles/modular/color_systems/kodachrome/[02] Natural.xmp" },
        { title = "Reduce Redness", path = "profiles/modular/color_systems/kodachrome/[02] Reduce Redness.xmp" },
        { title = "Soft Touch", path = "profiles/modular/color_systems/kodachrome/[02] Soft Touch.xmp" },
        { title = "Warm Control", path = "profiles/modular/color_systems/kodachrome/[02] Warm Control.xmp" },
        { title = "Warm Fix", path = "profiles/modular/color_systems/kodachrome/[02] Warm Fix.xmp" },
      },
      ['03'] = {
        { title = "Calm Colors", path = "profiles/modular/color_systems/kodachrome/[03] Calm Colors.xmp" },
        { title = "Color Separation", path = "profiles/modular/color_systems/kodachrome/[03] Color Separation.xmp" },
        { title = "Contrast", path = "profiles/modular/color_systems/kodachrome/[03] Contrast.xmp" },
        { title = "Depth", path = "profiles/modular/color_systems/kodachrome/[03] Depth.xmp" },
        { title = "Light Wrap", path = "profiles/modular/color_systems/kodachrome/[03] Light Wrap.xmp" },
        { title = "Soft", path = "profiles/modular/color_systems/kodachrome/[03] Soft.xmp" },
        { title = "Subject Focus", path = "profiles/modular/color_systems/kodachrome/[03] Subject Focus.xmp" },
        { title = "Subject Polish", path = "profiles/modular/color_systems/kodachrome/[03] Subject Polish.xmp" },
      },
      ['04'] = {
        { title = "Deep Shadows", path = "profiles/modular/color_systems/kodachrome/[04] Deep Shadows.xmp" },
        { title = "Soft Highlights", path = "profiles/modular/color_systems/kodachrome/[04] Soft Highlights.xmp" },
        { title = "Soft Pastel", path = "profiles/modular/color_systems/kodachrome/[04] Soft Pastel.xmp" },
        { title = "Texture", path = "profiles/modular/color_systems/kodachrome/[04] Texture.xmp" },
      },
    },
  },
  ["portra"] = {
    stages = {
      ['01'] = {
        { title = "Portra 160", path = "profiles/modular/color_systems/portra/2.ML_Portra160.xmp" },
        { title = "Portra 400", path = "profiles/modular/color_systems/portra/3.ML_Portra400.xmp" },
        { title = "Portra 800", path = "profiles/modular/color_systems/portra/4.ML_Portra800.xmp" },
      },
      ['02'] = {
        { title = "Clean Canvas", path = "profiles/modular/color_systems/portra/[02] Clean Canvas.xmp" },
        { title = "Highlight Soft", path = "profiles/modular/color_systems/portra/[02] Highlight Soft.xmp" },
        { title = "Indoor Balance", path = "profiles/modular/color_systems/portra/[02] Indoor Balance.xmp" },
        { title = "Natural", path = "profiles/modular/color_systems/portra/[02] Natural.xmp" },
        { title = "Reduce Redness", path = "profiles/modular/color_systems/portra/[02] Reduce Redness.xmp" },
        { title = "Shadow Open", path = "profiles/modular/color_systems/portra/[02] Shadow Open.xmp" },
        { title = "Soft Control", path = "profiles/modular/color_systems/portra/[02] Soft Control.xmp" },
        { title = "Soft Touch", path = "profiles/modular/color_systems/portra/[02] Soft Touch.xmp" },
        { title = "Warm Control", path = "profiles/modular/color_systems/portra/[02] Warm Control.xmp" },
        { title = "Warm Fix", path = "profiles/modular/color_systems/portra/[02] Warm Fix.xmp" },
      },
      ['03'] = {
        { title = "Calm Colors", path = "profiles/modular/color_systems/portra/[03] Calm Colors.xmp" },
        { title = "Color Separation", path = "profiles/modular/color_systems/portra/[03] Color Separation.xmp" },
        { title = "Depth", path = "profiles/modular/color_systems/portra/[03] Depth.xmp" },
        { title = "Film Fade", path = "profiles/modular/color_systems/portra/[03] Film Fade.xmp" },
        { title = "Light Wrap", path = "profiles/modular/color_systems/portra/[03] Light Wrap.xmp" },
        { title = "Soft", path = "profiles/modular/color_systems/portra/[03] Soft.xmp" },
        { title = "Subject Focus", path = "profiles/modular/color_systems/portra/[03] Subject Focus.xmp" },
        { title = "Subject Polish", path = "profiles/modular/color_systems/portra/[03] Subject Polish.xmp" },
      },
      ['04'] = {
        { title = "Deep Shadows", path = "profiles/modular/color_systems/portra/[04] Deep Shadows.xmp" },
        { title = "Soft Highlights", path = "profiles/modular/color_systems/portra/[04] Soft Highlights.xmp" },
        { title = "Soft Pastel", path = "profiles/modular/color_systems/portra/[04] Soft Pastel.xmp" },
        { title = "Texture", path = "profiles/modular/color_systems/portra/[04] Texture.xmp" },
      },
    },
  },
  ["vision3"] = {
    stages = {
      ['01'] = {
        { title = "Vision3 200T", path = "profiles/modular/color_systems/vision3/01_VISION3_200T_MASTER.xmp" },
        { title = "Vision3 200T Plus", path = "profiles/modular/color_systems/vision3/5.ML_Vision3_200T+.xmp" },
        { title = "Vision3 250D", path = "profiles/modular/color_systems/vision3/2.ML_Vision3_250D.xmp" },
        { title = "Vision3 500T", path = "profiles/modular/color_systems/vision3/1.ML_Vision3_500T.xmp" },
        { title = "Vision3 50D", path = "profiles/modular/color_systems/vision3/3.ML_Vision3_50D.xmp" },
        { title = "Vision3 BW", path = "profiles/modular/color_systems/vision3/7.ML_Vision3_BW.xmp" },
      },
      ['02'] = {
        { title = "Clean Canvas", path = "profiles/modular/color_systems/vision3/[02] Clean Canvas.xmp" },
        { title = "Highlight Soft", path = "profiles/modular/color_systems/vision3/[02] Highlight Soft.xmp" },
        { title = "Natural", path = "profiles/modular/color_systems/vision3/[02] Natural.xmp" },
        { title = "Reduce Redness", path = "profiles/modular/color_systems/vision3/[02] Reduce Redness.xmp" },
        { title = "Shadow Open", path = "profiles/modular/color_systems/vision3/[02] Shadow Open.xmp" },
        { title = "Soft Touch", path = "profiles/modular/color_systems/vision3/[02] Soft Touch.xmp" },
        { title = "Tungsten Clean", path = "profiles/modular/color_systems/vision3/[02] Tungsten Clean.xmp" },
        { title = "Warm Control", path = "profiles/modular/color_systems/vision3/[02] Warm Control.xmp" },
        { title = "Warm Fix", path = "profiles/modular/color_systems/vision3/[02] Warm Fix.xmp" },
      },
      ['03'] = {
        { title = "Calm Colors", path = "profiles/modular/color_systems/vision3/[03] Calm Colors.xmp" },
        { title = "Color Separation", path = "profiles/modular/color_systems/vision3/[03] Color Separation.xmp" },
        { title = "Crisp", path = "profiles/modular/color_systems/vision3/[03] Crisp.xmp" },
        { title = "Depth", path = "profiles/modular/color_systems/vision3/[03] Depth.xmp" },
        { title = "Light Wrap", path = "profiles/modular/color_systems/vision3/[03] Light Wrap.xmp" },
        { title = "Soft", path = "profiles/modular/color_systems/vision3/[03] Soft.xmp" },
        { title = "Subject Focus", path = "profiles/modular/color_systems/vision3/[03] Subject Focus.xmp" },
        { title = "Subject Polish", path = "profiles/modular/color_systems/vision3/[03] Subject Polish.xmp" },
      },
      ['04'] = {
        { title = "Deep Shadows", path = "profiles/modular/color_systems/vision3/[04] Deep Shadows.xmp" },
        { title = "Soft Highlights", path = "profiles/modular/color_systems/vision3/[04] Soft Highlights.xmp" },
        { title = "Soft Pastel", path = "profiles/modular/color_systems/vision3/[04] Soft Pastel.xmp" },
        { title = "Texture", path = "profiles/modular/color_systems/vision3/[04] Texture.xmp" },
      },
    },
  },
}
